### ISSUE TITLE
Test interleaving factors on Power and ARM

### ISSUE THREAD

**Issue by lei-april** [openwall/john#1770]
On Power:

gcc version 4.9.2 20141101 (Red Hat 4.9.2-1) (GCC)
John the Ripper 1.8.0-jumbo-1-3739-gbbb222d+ OMP [linux-gnu 64-bit powerpc64le-ac]
Default paras: SIMD: AltiVec, interleaving: MD4:1 MD5:1 SHA1:1 SHA256:1 SHA512:1
OMP_NUM_THREADS=8 GOMP_CPU_AFFINITY=0-7

| hash\para | 1 | 2 | 3 | 4 | 5 |
| --- | --- | --- | --- | --- | --- |
| md4 | **14620** | 8936 | 9312 | 11744 | 13760 |
| md4-omp | **30880** | 22656 | 19680 | 19584 | 19485 |
| md5 | **10900** | 5096 | 7021 | 8896 | 9980 |
| md5-omp | **19552** | 13568 | 13440 | 13312 | 12640 |
| sha1 | **9008** | 3752 | 4404 | 5248 | 5386 |
| sha1-omp | **10962** | 5893 | 5176 | 4768 | 4752 |
| sha256 | **3608** | 3120 | 3072 | 3104 | 3200 |
| sha256-omp | **3580** | 3325 | 2889 | 2760 | 2951 |
| sha512 | **1682** | 1216 | 1248 | 1296 | 1237 |
| sha512-omp | **1473** | 1172 | 1093 | 1066 | 1165 |

**Comment by zzlei** [comment]
I think I've done that on Power before, but didn't bind threads to specific cores. This time the results should be far more accurate.

**Comment by zzlei** [comment]
The native gcc on ZedBoard is buggy. I have to cross-compile on my laptop and transfer the executable to the board. Maybe I can modify testpara.pl somehow to accomplish this for me. I'll post the result on ARM later.

**Comment by zzlei** [comment]
On ARM:

gcc version 4.9.2 (Ubuntu 4.9.2-0ubuntu1~14.04)
John the Ripper 1.8.0-jumbo-1-3743-geaca7ff+ OMP [none 32-bit NEON-ac]
Default paras: SIMD: NEON, interleaving: MD4:1 MD5:1 SHA1:1 SHA256:1 SHA512:1

hash\para  |       1  |       2  |       3  |       4  |
-----------|----------|----------|----------|----------|
md4        |    1328  |  **1376**|    1057  |     864  |
md4-omp    |    2648  |  **2752**|    2114  |    1710  |
md5        |     836  |  **1008**|     708  |     512  |
md5-omp    |    1664  |  **1996**|    1401  |    1024  |
sha1       |   **252**|     240  |     209  |     188  |
sha1-omp   |   **499**|     480  |     415  |     376  |
sha256     |   **178**|     146  |     132  |     107  |
sha256-omp |   **352**|     295  |     264  |     215  |
sha512     |    **70**|      57  |      52  |      21  |
sha512-omp |   **139**|     115  |     105  |      40  |

The column for para=5 is omitted because it makes md4 and md5 segfault on ARM. I investigated it a bit and it seems to have something to do with strict aliasing. Either lowering optimization level from `-O2` to `O0` or explicitly specifying `-fno-strict-aliasing` can make the segfaults go away.

More specifically, when I was experimenting with pbkdf2-hmac-md5, simply using `-fno-strict-aliasing` on pbkdf2-hmac-md5_fmt_plug.c makes the format work.

**Comment by magnumripper** [comment]
That doesn't sound very good. What if you revert 96ad4ded (that is, revert the revertion) so it again uses mem_align() in eg. pbkdf2_hmac_*.h?

**Comment by zzlei** [comment]
Confirmed. It's commit 96ad4de that introduces this bug. I inspected the variables involved in the change of pbkdf2_hmac_md5.h, and they are properly aligned. Perhaps one form is strict-aliasing friendly, while the other is not (?) I don't know.

**Comment by magnumripper** [comment]
That's odd. I'll look into it and see if I can see why. Do the other PBKDF2 formats (that have similar code) work fine?

**Comment by magnumripper** [comment]
I see you mentioned MD4 and MD5.

**Comment by zzlei** [comment]
> Do the other PBKDF2 formats (that have similar code) work fine?

All my experimentations so far are based on your testpara.pl. So the formats we discussed are all pbkdf2-*. Among those, MD4 and MD5 are the only ones to segfault when para=5.

**Comment by magnumripper** [comment]
The fact it only happened at para 5 doesn't make it easier to understand... why would *that* affect strict aliasing?!

**Comment by solardiz** [comment]
The findings here were to use interleaving of 1 on Power, but 2 for MD4/MD5 on ARM. That's how we currently have it in code.

Another finding was that interleaving of 5+ would somehow expose strict aliasing violations or such resulting in miscompiles on ARM. This wasn't fully investigated, which is unfortunate as there may be a bug for us to fix. However, given that this issue isn't exposed in actual builds, let's not track it here.

**Comment by solardiz** [comment]
> interleaving of 5+ would somehow expose strict aliasing violations or such resulting in miscompiles on ARM

FWIW, there's one place where we do use interleaving of (exactly) 5 now - for MD5 when building for x86_64 with clang:

```c
#ifndef SIMD_PARA_MD5
#if defined(__INTEL_COMPILER)
#define SIMD_PARA_MD5                   3
#elif defined(__clang__)
#define SIMD_PARA_MD5                   5
```

We may need to revisit this for newer clang as it may not be best for performance anymore, but I'm not aware of this causing any misbehavior (I am running our test suite against such build now, with AVX512BW).
