### ISSUE TITLE
Regex mode is broken for Unicode after merging #2571 for librexgen 2.0.6

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#2640]
After merging #2571
```
$ ../run/john -stdout --regex=ab[cd]
abc
abd
2p 0:00:00:00 0.00% 200.0p/s abd

$ ../run/john -stdout --regex=ab[öc]
ab?
abc
2p 0:00:00:00 0.00% 100.0p/s abc
```
@teeshop did you test your PR at all? Is this just something with my setup?

**Comment by magnumripper** [comment]
Hmmm actually even rexgen standalone behaves the same
```
$ rexgen -v
rexgen-2.0.6

$ rexgen ab[öc]
ab?
abc
```

**Comment by teeshop** [comment]
This seems to be a problem with character class parsing:
```
$ rexgen 'ab(ö|c)'
abö
abc
```

I'llk take a look at it now

**Comment by magnumripper** [comment]
Ok, that one works with JtR too. So this is probably not a problem on JtR side.

This is a JtR problem however:
```
$ ../run/john -stdout --regex='ab(ö|c)' -target-enc=cp437
Target encoding: CP437
abö
abc
2p 0:00:00:00 0.00% 100.0p/s abc
```
It outputs UTF-8 even though asked to output CP437. Not a huge problem nowadays. I'll take care of that.

**Comment by teeshop** [comment]
```
$ rexgen -v
rexgen-2.0.7
$ rexgen 'ab[öc]'
abö
abc
```
Works 👍  However, It seems that you must call `setlocale(LC_CTYPE, "");` on a Mac in order to apply the users current environment locale. I've not tried this on Linux. At least, with rexgen on a Mac this works.

I'm not gonna do this inside of librexgen, because JtR may call `setlocale()` by itself with different parameters and librexgen has to use this setting instead of simply applying the users environment.

**Comment by magnumripper** [comment]
Aha... I recall we do set a locale when using librexgen. I'll look into it. Perhaps this can solve the other problem too - if we use an "internal codepage" we can also set that locale.

**Comment by magnumripper** [comment]
This bug is long gone
