### ISSUE TITLE
ETA is highly inaccurate (for slow hashes and large numbers of salts)

### ISSUE THREAD

**Issue by roycewilliams** [openwall/john#2896]
In some circumstances, john only shows the current time in the time estimate. Here is an example that is using this version of jumbo:

John the Ripper 1.8.0.6-jumbo-1-3356-gaf72cfc+ OMP [linux-gnueabihf 32-bit NEON-ac]

... target hashes that are bcrypt cost 8, and using `--progress-every=10`. 

As you can see, the estimated time slides along to match the current time. (Successful guesses have been omitted for brevity).

1088g 0:00:52:10 DONE (2017-11-17 17:03) 0.3475g/s 0p/s 159980c/s 159980C/s 123456..alex2004
1093g 0:00:52:20 DONE (2017-11-17 17:03) 0.3480g/s 0p/s 159979c/s 159979C/s holden..alex2004
1097g 0:00:52:30 DONE (2017-11-17 17:03) 0.3482g/s 0p/s 159976c/s 159976C/s 123456..alex2004
1103g 0:00:52:40 DONE (2017-11-17 17:04) 0.3490g/s 0p/s 159973c/s 159973C/s 123456..alex2004
1108g 0:00:52:50 DONE (2017-11-17 17:04) 0.3494g/s 0p/s 159971c/s 159971C/s 123456..alex2004
1111g 0:00:53:00 DONE (2017-11-17 17:04) 0.3493g/s 0p/s 159965c/s 159965C/s 123456..alex2004
1114g 0:00:53:10 DONE (2017-11-17 17:04) 0.3492g/s 0p/s 159963c/s 159963C/s 123456..alex2004
1119g 0:00:53:20 DONE (2017-11-17 17:04) 0.3496g/s 0p/s 159962c/s 159962C/s 123qwerty..alex2004
1121g 0:00:53:30 DONE (2017-11-17 17:04) 0.3492g/s 0p/s 159960c/s 159960C/s 123456..alex2004
1125g 0:00:53:40 DONE (2017-11-17 17:05) 0.3493g/s 0p/s 159957c/s 159957C/s 123456..alex2004
1128g 0:00:53:50 DONE (2017-11-17 17:05) 0.3492g/s 0p/s 159957c/s 159957C/s 123456..alex2004
1135g 0:00:54:00 DONE (2017-11-17 17:05) 0.3502g/s 0p/s 159957c/s 159957C/s 123456..alex2004
1141g 0:00:54:10 DONE (2017-11-17 17:05) 0.3510g/s 0p/s 159953c/s 159953C/s ji394su3..alex2004
1145g 0:00:54:20 DONE (2017-11-17 17:05) 0.3511g/s 0p/s 159952c/s 159952C/s 123456..alex2004
1148g 0:00:54:30 DONE (2017-11-17 17:05) 0.3510g/s 0p/s 159954c/s 159954C/s 123456..alex2004
1150g 0:00:54:40 DONE (2017-11-17 17:06) 0.3506g/s 0p/s 159951c/s 159951C/s abc123456..alex2004
1152g 0:00:54:50 DONE (2017-11-17 17:06) 0.3501g/s 0p/s 159951c/s 159951C/s 123456..alex2004
1157g 0:00:55:00 DONE (2017-11-17 17:06) 0.3505g/s 0p/s 159950c/s 159950C/s 123456..alex2004
1160g 0:00:55:10 DONE (2017-11-17 17:06) 0.3504g/s 0p/s 159951c/s 159951C/s 123456..alex2004
1163g 0:00:55:20 DONE (2017-11-17 17:06) 0.3502g/s 0p/s 159952c/s 159952C/s 123456..alex2004
1168g 0:00:55:30 DONE (2017-11-17 17:06) 0.3507g/s 0p/s 159952c/s 159952C/s 123456..alex2004
1172g 0:00:55:40 DONE (2017-11-17 17:07) 0.3508g/s 0p/s 159955c/s 159955C/s 123456..alex2004
1173g 0:00:55:50 DONE (2017-11-17 17:07) 0.3501g/s 0p/s 159955c/s 159955C/s 123456..alex2004
1175g 0:00:56:00 DONE (2017-11-17 17:07) 0.3496g/s 0p/s 159952c/s 159952C/s monster..alex2004
1179g 0:00:56:10 DONE (2017-11-17 17:07) 0.3498g/s 0p/s 159953c/s 159953C/s 123456..alex2004

The actual attack was about 720K hashes, 50K words, and completed in about 71 hours.

**Comment by solardiz** [comment]
This is a well-known limitation of ETA tracking in that it doesn't take into consideration progress over salts. This is not in any way specific to ZTEX, but applies to any slow hash when the number of salts and the number of keys per crypt (including those possibly generated by `crypt_all()` itself) are both large. Until recent enhancement by @jfoug, we had a similar issue with interrupt/restore, where the work would essentially be redone from scratch. That enhancement suggests that rather than close this issue without a fix like we normally would, maybe we should use this opportunity to enhance the ETA reporting as well? The issue title may be changed to be more generic accordingly. Jim, magnum - will you? If not, let's just close this one again. ;-(

**Comment by frank-dittrich** [comment]
See https://github.com/magnumripper/JohnTheRipper/issues/2747 for some more comments regarding this issue (or rather, expected behaviour)

What is the max. keys per crypt value for this format? (See ./john --list=format-all-details --format=<your format>)

BTW: The `+` in john's version string indicates local uncommitted changes in your repository.
Are you aware of any local changes you did on purpose?
If not, can you post the output of `git status -uno` or `git diff`?.

**Comment by solardiz** [comment]
`max_keys_per_crypt` for this format is commonly roughly in the range 2^18 to 2^21.

I guess Royce edited `TargetSetting` in `john.conf` to tune for his bcrypt cost 8, as he should have.

**Comment by roycewilliams** [comment]
Yep, confirmed that I'm running with john.conf using `TargetSetting = 8`.

**Comment by frank-dittrich** [comment]
I guess we should document how a user can overwrite such config settings in john-local.conf, so that `git diff` doesn't show differences and a `git pull` doesn't cause trouble for normal users running latest bleeding-jumbo.

**Comment by solardiz** [comment]
"Show current time" is just one special case. If Royce had e.g. a few million words in the wordlist rather than merely 50k, this would be different.

**Comment by solardiz** [comment]
Closing in favor of #5378.
