### ISSUE TITLE
Supply proper OpenCL headers ourselves, and detect too old OpenCL lib

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#3918]
The configure script should ensure we have OpenCL >= 1.2 in headers **and** lib, and then some of our headers should enforce the actually sourced OpenCL header also is >= 1.2

**Comment by solardiz** [comment]
As I wrote in https://github.com/magnumripper/JohnTheRipper/issues/3915#issuecomment-491499246:

As I understand, hashcat bundles the Khronos Group headers under deps/OpenCL-Headers in its tree. Maybe we should consider doing the same.

Maybe that would be a better post-release change than adding an autoconf check for the system's headers version.

**Comment by magnumripper** [comment]
Agreed. We should include the official headers and just check for libs.

**Comment by alainesp** [comment]
I can add the Khronos Group headers and fix this issue. Does JtR use git submodules or prefer to copy the code in a folder?

**Comment by solardiz** [comment]
> I can add the Khronos Group headers and fix this issue. Does JtR use git submodules or prefer to copy the code in a folder?

Thank you! No submodules, please add a subdirectory, I guess `src/CL` and I guess we'll need to change `<>` to `""` inside the files (separate commit, please) so that we don't have to specify a `-I` when building.

Once we have that, we could want to allow to build with OpenCL even when the library isn't found at `configure` time. Maybe we should support both `--enable-opencl` and `--disable-opencl`, with the default depending on whether the library is found at `configure` time.

So maybe 4 commits total:
1. Add `src/CL` with Khronos Group files as they are.
2. Change `<>` to `""` inside the files.
3. Change `<>` to `""` when referring to those files from our existing source files, and drop the `__APPLE__` special case.
4. Enhance `configure` as above (edit `configure.ac`, regenerate `configure` with same version of autoconf as before - e.g., on "super").

**Comment by solardiz** [comment]
Items 1, 2, 3 above have been taken care of by @alainesp in #5396, so I'm closing this issue. We haven't yet decided on the `configure` script changes.

**Comment by ghost** [comment]
We are not really checking "old OpenCL library" yet. Something like this is required:

But, there is one testing issue:
- no OpenCL < 1.2 available. Does `bull` have it? 
 
So, in fact, it was not really tested here.

```
diff --git a/src/opencl_dynamic_loader.c b/src/opencl_dynamic_loader.c
index 43b5b8a87d..25880927f7 100644
--- a/src/opencl_dynamic_loader.c
+++ b/src/opencl_dynamic_loader.c
@@ -609,6 +609,15 @@ static void load_opencl_dll(void)
                puts("Cannot load OpenCL library");
                return;
        }
+       char *error;
+       dlsym(opencl_dll, "OPENCL_1.2"); // Value is NULL
+       error = dlerror();
+
+       if (error) {
+               fprintf(stderr, "Warning: Cannot find the OPENCL_1.2 data object\n");
+               opencl_dll = NULL;
+               return;
+       }

```
**[edited]**

[0001-OpenCL-blablabla.txt](https://github.com/openwall/john/files/13730993/0001-OpenCL-blablabla.txt)
****

The best I can do is try to detect an invalid version. Then:

```
Warning: Cannot find the OPENCL_1.7 data object
Error: No OpenCL-capable platforms were detected by the installed OpenCL driver.
Error: No OpenCL-capable devices were detected by the installed OpenCL driver.
```

It is 1.1 (from `opencl_common.c`)
```
			/*
			 * JtR requires OpenCL 1.1+. It doesn't properly support devices
			 * that don't fully support OpenCL 1.1.
			 */
```

**Comment by solardiz** [comment]
> We are not really checking "old OpenCL library" yet.

Do we really want to? Why? With the current code, we'll print warnings about any missing OpenCL 1.2 functions that we could possibly use, but we'd proceed anyway.
