### ISSUE TITLE
Add support for VCU1525 FPGA boards

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4019]
Now that we've made a release with support for 7 hash types on ZTEX 1.15y boards, our next target could be VCU1525/BCU1525 boards and Amazon AWS F1.

@dedmarozz would you possibly be interested in getting involved? As I understand, you've been into miner development for various FPGA boards including ZTEX 1.15y and VCU1525, so I thought maybe you'd be interested in our password cracker project as well? On a related note, I'd be happy if your [108 ZTEX boards end up with JtR users](https://www.openwall.com/lists/john-users/2019/06/05/2) or/and you become a JtR user (if not already).

**Comment by dedmarozz** [comment]
Hi, im very busy so i dont know if i have some free time for another
developing. I have real job and this is only my hobby. Pls add bittware
CVP-13 fpga board to your support list in future. This board is much better
than VCU/BCU

https://www.bittware.com/fpga/xup-vvp/

Best Regards

DedMaroz

st 5. 6. 2019 v 21:04 odesílatel Solar Designer <notifications@github.com>
napsal:

**Comment by solardiz** [comment]
Thanks for the reply, @dedmarozz. I fully expected you wouldn't have much free time for this, yet I think we might find an arrangement that would work for you. We probably don't need a lot of your time, but rather some help in jump-starting the project for @Apingis (who implemented the ZTEX 1.15y support for us) on our team to continue it, or/and remote access to your boards (we currently don't have access to any of these newer boards, except possibly via AWS). I understand your miner development is probably for-profit, and am open to discussing possible arrangements where your time would be appropriately compensated. (BTW, our support for the ZTEX boards might already bring you some money through being able to sell them easier and for more.) I might talk to prospective sponsors for this effort, but right now we're in a catch-22 situation where we're not confident we'd make the project work so can't reasonably commit to it to a sponsor yet. We need a working prototype (perhaps one JtR "format") on those boards first.

Regarding VU13P-based boards, I heard those are nearly impossible to cool under nearly-full device utilization (does Bittware's water cooling overcome that?), and they're even pricier and not as widespread. So they don't appear to be a worthy target for us yet, unless their support would be easy to add on top of the VU9P-based boards once we support those. Maybe their support would provide valuable academic results as it'd be higher per-chip speeds than we'd have achieved otherwise.

For password cracking rather than mining use, even the purchase price of one VU9P-based board is prohibitive to most of our prospective users, who would use the board only occasionally rather than 24/7. So being able to use AWS F1 instances is very important.

I notice you replied via e-mail. Can we perhaps take this to e-mail? I'm "solar at openwall.com".

**Comment by dedmarozz** [comment]
i dont know "openwall.com" if you chat with me, i using fpga crypto discord
channel, i have my own developer room here: https://discord.gg/SS4kt9

i have one VCU1525 board, one bittware cvp-13 and two Enterpoint CM5 boards
at home. VCU1525 is worst hardware, not designed for mining and for high
load, have only 150A power source, so you never used 100% potential this
fpga, i ending support for this board because is piece of crap hardweare.
CVP-13 is much bette, have 400A power source and good water cooling but is
expensive. Best performance/price is Enterpoint CM5, very good hardware
design, 480A power supply, 2x Intel Arria10, same performance as VCU1525
and only 1600$!

bittware and Enterpoint company sporsored my work, i recieve free boards
for developing

https://bitcointalk.org/index.php?topic=5069004.0




so 8. 6. 2019 v 17:04 odesílatel Solar Designer <notifications@github.com>
napsal:

**Comment by dedmarozz** [comment]
btw all my 108 ztex boards are sold or reserved, 28 to US, one to Ukraine
and 80 to Netherlands :) i selling 100$ per board

so 8. 6. 2019 v 23:41 odesílatel Jmeno Prijmeni <dedmaroz.85@gmail.com>
napsal:

**Comment by solardiz** [comment]
This isn't currently planned and it's been 5 years, so we'd need to re-evaluate for currently relevant hardware anyway.
