### ISSUE TITLE
zip2john pkzip2 output errors

### ISSUE THREAD

**Issue by cosmopol** [openwall/john#4050]
I think I have found a bug! I have a large password-protected PKZIP64 file which seems to crash zip2john.exe. It prints out some 1GB of hash string without actually delimiting the hash string properly (the $/pkzip2$ end tag is missing entirely). I can provide the file for test puposes via PM. btw: pentesting is real fun!

**Comment by magnumripper** [comment]
OK. To be more exact, how large is the faulty output file?

**Comment by magnumripper** [comment]
And you are using the 1.9 stuff, right?

**Comment by cosmopol** [comment]
using john-1.9.0-jumbo-1-win64

I have found the $/pkzip2$ tag eventually - my text editor seems to cut the end of the hash file off, it can be seen with a hex editor, anyhow it is 1.01 GB (1.090.051.700 bytes) in size, that seems wrong to me

**Comment by solardiz** [comment]
There's no indication of a bug in what you describe, @cosmopol.

magnum, maybe we need to have zip2john and rar2john (any others?) output a message to stderr that it's normal for the resulting "hashes" to be very large? Maybe only output this when they're in fact very large. Otherwise people get confused, expecting "hashes" to be tiny. Edit: this is now tracked as #4051.

Longer-term (perhaps for JtR 2.1 or so?), maybe we need to merge these programs into JtR's loader, so that there's no need to create these large intermediate files for archives.

**Comment by solardiz** [comment]
@cosmopol Please confirm that `john` loads the "hash" fine for you, and close the issue if so. Thanks!

**Comment by cosmopol** [comment]
I am indeed confused by the very large hash string. Every example I have seen so far involves tiny hash strings. John seems to do (seemingly) fine. Sorry, I got confused by the faulty text editor output which seems to have truncated the end tag.

john's output:
Using default input encoding: UTF-8
Loaded 1 password hash (PKZIP [32/64])

**Comment by magnumripper** [comment]
> Longer-term (perhaps for JtR 2.1 or so?), maybe we need to merge these programs into JtR's loader, so that there's no need to create these large intermediate files for archives.

I'd love that. Unfortunately most tools that produce crazy large non-hashes are currently written in Python, and the reason they are is the files are fairly complicated to parse so we gain a lot in using existing frameworks.
