### ISSUE TITLE
oldoffice-opencl, OpenCL CL_OUT_OF_HOST_MEMORY (-6) error in opencl_oldoffice_fmt_plug.c:138 - Error mapping saved_key

### ISSUE THREAD

**Issue by dosoos** [openwall/john#4056]
### John Version ###
\# john
John the Ripper 1.9.0-jumbo-1+bleeding-9b4335e7c 2019-07-18 11:52:24 +0200 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2019 by Solar Designer and others
Homepage: https://www.openwall.com/john/

### When i use dictioary crack oldoffice hash have this problem ###
Using default input encoding: UTF-8
Loaded 1 password hash (oldoffice-opencl, MS Office <= 2003 [MD5/SHA1 RC4 OpenCL])
Cost 1 (hash type) is 0 for all loaded hashes
Node numbers 1-8 of 8 (fork)
Device 4: P106-100
Device 8: P106-100
Device 1: P106-100
Note: This format may be a lot faster with --mask acceleration (see doc/MASK).
Device 7: P106-100
Device 5: P106-100
Device 6: P106-100
Device 3: P106-100
Device 2: P106-100
8: OpenCL CL_OUT_OF_HOST_MEMORY (-6) error in opencl_oldoffice_fmt_plug.c:138 - Error mapping saved_key
1: OpenCL CL_OUT_OF_HOST_MEMORY (-6) error in opencl_oldoffice_fmt_plug.c:138 - Error mapping saved_key

## my machine have 8GB memory ##
maybe need more memory? or this is issue? bug?

**Comment by dosoos** [comment]
### hash content ###
xxooxxoo.file:$oldoffice$0*66fff42aaf5231cd7cb14cf410d2a443*d143df50c79960663c127997433aaeca*5dc969945f79f6f40ff9044cc41c1ac4:::::xxooxxoo.xls

**Comment by solardiz** [comment]
@dosoos It does sound like you need more memory, but you might be able to reduce JtR's memory needs by first running with "-v=4" (higher verbosity level), noting the auto-tuned values of GWS, and then explicitly specifying a lower value with "GWS=lowervaluehere john ...". You'd want the lower value to be e.g. 1/2 or 1/4 of the auto-tuned value.

Edit: for the verbose auto-tuning to complete without running out of memory, you'd omit `--fork` on that one run. You'd re-add `--fork` when you specify GWS explicitly.

@magnumripper @claudioandre-br We might want `--save-memory` to affect auto-tuning, resulting in lower GWS if the speedup of using a higher GWS would have been small yet the value would be large in absolute terms. If by default we require a 1%+ speedup for use of a higher GWS, then with memory saving enabled (at level 2 or higher? since level 1 is historically for not loading login names only) and values being significant in absolute terms (e.g., at least 10240?) we could use a 5%+ threshold instead.

Edit: this suggestion is now issue #4057.

**Comment by magnumripper** [comment]
In general we could recommend having as much host memory as the sum of OpenCL device's memory, at the very least.

**Comment by solardiz** [comment]
@dosoos After the recent merging of #4060 you should now be able to avoid this issue by using `--save-memory=2` or  `--save-memory=3`. These have a slight performance impact.

Thanks @claudioandre-br for implementing the above!

Maybe we should also have JtR recommend that option upon getting a CL_OUT_OF_HOST_MEMORY error?

@magnumripper I think "having as much host memory as the sum of OpenCL device's memory" is generally excessive. Just because a device has a lot of memory doesn't mean all of it will correspond to host-side buffers in typical JtR jobs - in fact, that would be very unusual.

**Comment by magnumripper** [comment]
> @magnumripper I think "having as much host memory as the sum of OpenCL device's memory" is generally excessive. Just because a device has a lot of memory doesn't mean all of it will correspond to host-side buffers in typical JtR jobs - in fact, that would be very unusual.

I believe that's what hashcat team use to say, tho' I agree when you put it that way.

However, if you just have a single card with, say, 11 GB, you really should have at least 16 GB anyway, for buffers or not. And if you have a super crack rig with 8 GPU's having 11 GB each, you can probably afford 96 GB of RAM as well, and it will be beneficial for sure - even if not used as GPU buffers.

**Comment by solardiz** [comment]
I think this sort of recommendations are akin to the historical rule of thumb to make a swap partition 2x the size of RAM or such, whereas one might not need much or any swap space at all.

Just because one purchased GPUs with a lot of memory on the cards doesn't mean they intend to fully use that memory soon, if ever. They just wanted fast GPUs and those came with memory soldered on. Host memory can be upgraded later if and when actually needed. But yes, not to have to bother later and not trying to build many cost-effective rigs, but rather just one rig that won't require further upgrades for a while, it does make sense to spend an extra GPU's worth on more RAM just in case and for other uses.

**Comment by solardiz** [comment]
BTW, P106-100 has 6 GB, not the 11 GB magnum mentioned as an example. I think it's typical to have many of those with little host RAM and a cheap dual-core CPU in a mining-mostly rig, where the GPU memory would be used for Ethereum's Ethash's DAG (currently inbetween 3 GB and 4 GB) without needing much from the host. Would occasional reuses of a mining rig like that for password cracking justify adding more host RAM? That depends.
