### ISSUE TITLE
高版本office2013生成的低版本2003格式的xls文件,无法计算hash值

### ISSUE THREAD

**Issue by 1006079161** [openwall/john#4105]
高版本office2013生成的低版本2003格式的xls文件,无法计算hash值
比如：https://beiyongcdn.oss-cn-hongkong.aliyuncs.com/exp.xls    password:123456789

**Comment by 1006079161** [comment]
发现自己下载的旧版本,新版本原来修复了
elif data[0:4] == b'\x01\x00\x02\x00' or data[0:4] == b'\x01\x00\x03\x00' or data[0:4] == b'\x01\x00\x04\x00':

**Comment by solardiz** [comment]
Google Translate of these comments:

"High version office2013 generated low version 2003 format xls file, can not calculate hash value"

"I found the old version I downloaded, and the new version was fixed."

So I assume this is already fixed in our current code, yet we should probably re-check using the "exp.xls" file from the first comment.

**Comment by magnumripper** [comment]
Yep, works fine
