### ISSUE TITLE
rar2john No password hashes loaded

### ISSUE THREAD

**Issue by DemonRem** [openwall/john#4162]
guys I using the latest version of the windows software and I managed to generate the hash file
but the tool not found any password in it, if someone can can crack it for me or telling me what I doing wrong I be glad
![1](https://user-images.githubusercontent.com/29927382/69483402-b0c25900-0e2f-11ea-81b1-ea9bd1a8fcb9.png)
[hash.txt](https://github.com/magnumripper/JohnTheRipper/files/3882805/hash.txt)

**Comment by ghost** [comment]
It is RAR5, not rar.
```
$ john --format=RAR5 Downloads/hash.txt
Using default input encoding: UTF-8
Loaded 3295 password hashes with no different salts (RAR5 [PBKDF2-SHA256 128/128 SSE2 4x])
Cost 1 (iteration count) is 32768 for all loaded hashes
Will run 2 OpenMP threads
Proceeding with single, rules:Single

```
****
The GitHub issues are primarily to keep track of bugs or other shortcomings of our software, and fix those. It is not to help individual users with their specific tasks. To receive user support from the community, please use the john-users mailing list instead.

**Comment by DemonRem** [comment]
thank @claudioandre-br solve my issue.

**Comment by solardiz** [comment]
Somehow it is a common user error to use the `--format` option unnecessarily. We have this error message refer to the FAQ, and we have an answer corresponding to this user error in the FAQ - but since we keep getting this sort of problem reports, this is somehow not working for some users. Maybe we need to also make a code change to test whether a `--format` was specified and alter the message if so suggesting that the `--format` option be dropped.

The FAQ:

```
Q: Why doesn't John load my password file?  It says "No password hashes
loaded", "No password hashes loaded (see FAQ)", or "No password hashes
left to crack (see FAQ)".
[...]
A: If you're using the "--format" option, try dropping it.  Except for
the special case mentioned in the answer above, "--format" is normally a
way to choose one of multiple hash/cipher types found in the same file
or to clarify the hash/cipher type if it would otherwise be ambiguous
(e.g., a 32 hexadecimal character string may correspond to one of many
distinct hash types).  That is, you normally only need to use "--format"
when John would otherwise misdetect your hash/cipher type (e.g., when it
says LM and you know that your hashes are in fact raw MD5, you'd use
"--format=raw-md5" with -jumbo) or if it would load undesired entries
from the file.  If John does not load anything, then your use of
"--format" is probably unreasonable (or you should be using a different
version/build of John - see the answer below).
```

This is currently the fourth answer (out of 8) to that question. Maybe we need to move it up the list, but would this have helped in this particular case, @DemonRem? Can you explain why you apparently did not(?) look in the FAQ despite of the explicit reference? Also, can you explain what made you use the `--format` option - I guess some third-party blog post or the like (in which case I'd wonder where those bloggers, etc. tend to get this idea from)?
