### ISSUE TITLE
Character shuffle rule or mode

### ISSUE THREAD

**Issue by torerobo** [openwall/john#4194]
I have a single wordlist "abb"
I checked all the rules
`-$ john --list=rules`

But I did not find the rule, which in general is very much in demand from the given characters:
Creating all kinds of combinations of characters

Example
`-$ john -w='/wordlist' --stdout --rules=Shuffle`

Expectation
a
b
ab
bb
ba
bab
bba
abb

I went looking for competitors: hashcat-Utils and crunch cannot do this either.
I suggest adding this rule to JtR.

ps / maybe a question / wish should have been asked on the mailing list, but I lost the e-mail address to which I need to write, but could not find, subscribing to the newsletter in a new way is troublesome.

**Comment by ghost** [comment]
You can achieve that using `prince` mode. 

```
$ cat wordlist 
a
b
```
```
$ john -prince=wordlist --stdout | head -20
Press 'q' or Ctrl-C to abort, almost any other key for status
510p 0:00:00:00 100.00% (2020-01-04 16:02) 4636p/s bbbbbbbb
a
b
aa
ba
ab
bb
aaa
baa
aba
bba
aab
bab
abb
bbb
aaaa
baaa
abaa
bbaa
aaba
baba
```
*****
> a question should have been asked on the mailing list,

I would say you should. This type of discussion is best suited for the mailing list. Either way, you can make your point clearer (or close the issue).

**Comment by torerobo** [comment]
Analogue Prince > `$ john -1=abb --mask=?1 -min-len=1 -max-len=3 --stdout`

> 0p 0:00:00:00 0,00% (1) 0p/s
> a
> b
> 2p 0:00:00:00 33,33% (2) 
> aa
> ba
> ab
> bb
> 6p 0:00:00:00 42,86% (3) 
> aaa
> baa
> aba
> bba
> aab
> bab
> abb
> bbb
> 14p 0:00:00:00 100,00% (3)...

```
$ cat wordlist
abb
```
```
$ john -w='/wordlist' --stdout --rules=Shuffle
a
b
ab
bb
ba
bab
bba
abb
```
There should be all kinds of combinations of all the characters in the proposed word (without duplication of multiplication).
There is no such rule (surprise) in JtR.  There are no competitors with this rule.  So JtR can get even cooler (this is a very popular rule).

**Comment by magnumripper** [comment]
Rules are **really really** slow. PRINCE mode is very fast. Mask mode is also as fast, and has GPU acceleration to boot. Yet another way to do it is `john -subsets=ab` which is about as fast as PRINCE mode and you don't need to create the wordlist. So why would we need this rule? Perhaps we don't quite understand your expectations: What combinations would you want `--rules=Shuffle` to produce, and what combinations do you NOT want in there?

**Comment by magnumripper** [comment]
BTW I *think* the new-ish "hybrid external mode" is capable of doing whatever you want. It's only a matter of some coding...

**Comment by magnumripper** [comment]
OK I think I see what you want: If you gave it "abb" you don't want "aab" or "bbb" in there, right? Only "abb", "bab" and "bba", correct? Also, mask or PRINCE modes can't do this with an entire wordlist and shuffle each word in it.

**Comment by magnumripper** [comment]
This is actually an interesting candidate for hybrid external mode. Should be fairly easy to code. If someone does, we'd definitely include it.

**Comment by torerobo** [comment]
> OK I think I see what you want: If you gave it "abb" you don't want "aab" or "bbb" in there, right? Only "abb", "bab" and "bba", correct? Also, mask or PRINCE modes can't do this with an entire wordlist and shuffle each word in it.

yes!

I did not find this in another software (crunch / hashcat).  Therefore JtR could be / 1

**Comment by solardiz** [comment]
> If you gave it "abb" you don't want "aab" or "bbb" in there, right? Only "abb", "bab" and "bba"

Sounds somewhat specialized to have as a built-in mode. Why/when/how would this be better than searching all combinations of those characters (without regard to their number of appearances in the original "word")? Perhaps it would for a forgotten password where the person recalls they had shuffled characters in a specific word (or in one of very few possible words). Is that the only somewhat likely and reasonable use case? With many words, the shuffling will quickly lead to duplicates (OK, we can suppress most) and to (almost?) exhausting the combinations anyway.

As to rules, those currently produce at most 1 candidate (the ruleset lines producing more candidates rely on the rule preprocessor, so are effectively multiple rules). If we ever introduce multi-output rules, then maybe this can be one of them.

Meanwhile, like magnum said, this could be a hybrid external mode. If we ever introduce multi-output rules, we'd probably have one to invoke an arbitrary hybrid external mode from there.

**Comment by solardiz** [comment]
Here's a first working attempt, with room for optimization perhaps via use of lookup tables:

```
[List.External:Shuffle]
int length, base[0x80], id[0x80];

void new()
{
	int c, i;

	length = -1;
	while (c = word[++length]) {
		base[length] = c;
		id[length] = 0;
	}
}

void next()
{
	int seen, i, j, k;

	if ((i = length) <= 10)
	while (i--) {
		if (++id[i] < length - i) {
			i = -1;
			seen = 0;
			while (++i < length) {
				j = -1;
				k = id[i];
				while (++j < length) {
					if (seen & (1 << j))
						continue;
					if (!k--)
						break;
				}
				word[i] = base[j];
				seen |= 1 << j;
			}
			return;
		}
		id[i] = 0;
	}

	word = 0;
}
```

With repeated characters in the input word, this generates some duplicates. However, for lengths up to 10 (as limited in the code above), our dupe suppressor is almost 100% effective at default settings (but need to enable it, e.g. with `-dup` on the command line).

**Comment by solardiz** [comment]
> With repeated characters in the input word, this generates some duplicates.

I've now pushed a more elaborate version that avoids the duplicates. There's still lots of room for performance optimization, but functionality wise this is complete, so this issue is now closed.

**Comment by solardiz** [comment]
> If you gave it "abb" you don't want "aab" or "bbb" in there, right? Only "abb", "bab" and "bba"

This is what I implemented, and further I suppress the original word as-is, so in this example there's no "abb". It is expected that the wordlist would be run as-is separately.

> Expectation a b ab bb ba bab bba abb

I did not implement any logic for lengths other than the input word's. So in this example, there are only "bab" and "bba".

**Comment by solardiz** [comment]
> There's still lots of room for performance optimization

Many of the optimizations I thought of are now in place. I've also added a simplified/reference version for easier understanding and cross-testing. Running both on `john.conf` (as of 0fdaad58c5c0221c29b5a0bf5892215cba4f48b1) as wordlist (a weird stress-test) and piping into `md5sum`, I get these:

```
$ ./john -w=john.conf -ext=shuffle -stdo | md5sum 
133021879p 0:00:00:36 100.00% (2024-05-29 21:10) 3646Kp/s }	
8c01dcc2d845fe7416e1444c2f6cd9c9  -
```

```
$ ./john -w=john.conf -ext=shuffle-simple -stdo | md5sum 
133021879p 0:00:03:39 100.00% (2024-05-29 21:13) 606049p/s }	
8c01dcc2d845fe7416e1444c2f6cd9c9  -
```

Edit: optimized further to:

```
133021879p 0:00:00:15 100.00% (2024-05-30 18:14) 8768Kp/s }	
8c01dcc2d845fe7416e1444c2f6cd9c9  -
```

**Comment by solardiz** [comment]
> I've now pushed a more elaborate version that avoids the duplicates.

While there are now no duplicates for each one input word, there are indeed duplicates across a larger wordlist, so running with `--dupe-suppression` is recommended when there's more than one input word and the target hash type is slow (or there are many different salts).

For the `john.conf` stress-test above, it's `133021879` including dupes, `52528149` after `-dup` (256 MiB), and `49072667` unique.

However, for a real wordlist, things are much better - e.g., for the first 100 non-empty passwords in `password.lst`, Shuffle's output is `4500326` including dupes, but `4498889` unique (99.97%). Dupes result from input lines that use the exact same character set as other lines (in this example, `abc123`, `a1b2c3`, and `123abc`).

**Comment by solardiz** [comment]
Testing with our default `password.lst` against a 10M representative sample from HIBPv8 (6969140 unique NTLM hashes), after having excluded `password.lst` as-is and reversed (rule `r`), by length, for up to 10M candidates per length (bumped into this limit starting with length 6), dupe suppressor not enabled:

4 and below: 4523
5: 14098
6: 40314
7: 5398
8: 742
9: 490
10: 327
11: 0
12: 0

These are unique password counts. I did crack some length 11 with a longer run.

The current default length limit configurable in the external mode `init` is 10, but based on the above I recommend running separately with `--max-length=6`, `--length=7`, and `--min-length=8`. Those 3 runs limited to 10M candidates each crack:

Up to 6: 41867
7: 5398
8 to 10: 1058

or maybe it's better to split further:

Up to 5: 18621
6: 40314

After having excluded 100M candidates of `--rules=best-by-score` + 100M of `--rules-stack=best-by-score` (each ran to approx. 2% progress before hitting 100M):

Up to 5: 3056
6: 16748
7: 2655
8 to 10: 842

After having excluded all `--rules=best-by-score` (with the same `password.lst` as in all of these tests):

Up to 5: 423
6: 1748
7: 651
8 to 10: 439

Letting them run to up to 100M candidates each (49.25% through wordlist for length 6, 10.23% for 7, 0.18% for 8+):

Up to 5: 423
6: 9529
7: 3366
8 to 10: 780

separating length 8, 9, 10:

8: 1813 (1.08%)
9: 419 (0.38%)
10: 337 (0.18%)

Somehow the cumulative result for 8 to 10 in the first test (10M total) was better than for 8 alone, but after having excluded more rules-crackable passwords and upgrading to 100M per Shuffle run, it's worse than for 8 alone.

Up to 6: 9661 (48.37%) just to have it limited to 100M for a further comparison:

That's 9661+3366+1813+419+337=15596 for 500M. Instead of the Shuffle runs, continuing with `--rules=worse-by-score` for 500M candidates (dupe suppressor disabled) cracks 17695, so Shuffle is a little less effective than simply continuing with rules. It can be made more effective (per candidate) by limiting it to lower lengths. OTOH, further rules can be made more effective by running another ruleset rather than the known-worse portion from the same original/split ruleset. 500M of `--rules=OneRuleToRuleThemStill` (including dupes) cracks 26185. 500M of default `--incremental` cracks 81403 (and the unique cracked by Shuffle reduce to 10081). All of these 500M options were tried on their own, never one on top of another (except for the retroactive comparison of incremental significantly reducing Shuffle's unique).

For a further comparison, continuing the default `--incremental` for a second 500M cracks 36535 more, which is 3.6x more than Shuffle's unique by that point (after first 500M incremental). 500M Shuffle's remaining unique reduce to 8878 on top of the 1G of incremental. Letting it run for yet another 500M (for 1.5G incremental) adds another 27663, which is again much more than Shuffle's was, and leaves 7923 Shuffle unique.

Overall, not surprisingly Shuffle is less effective than the alternatives, but maybe it adds some unique cracks on top of other exhausted possibilities? Let's try 10G of incremental on top of the `best-by-score` rules baseline. This cracks 314521. A further 500M of incremental (10.5G total) cracks 6291. 500M Shuffle's remaining unique after 10G were 4741. So even after 10G Shuffle is still less effective than simply continuing with incremental, although if we compare against Shuffle limited to lower lengths it'd probably break even. Let's try, on top of our rules baseline:

Up to 6: 15216 (200M, 93.73%)
7: 7836 (300M, 29.86%)

That's 23052 total, which is on par with further rules (although those produce dupes, which we'd suppress when running against slower targets, for more unique candidates and thus cracked passwords total). It's still much lower than continuing with incremental after rules. After the 10G incremental, there are only 5483 of the above Shuffle's unique, which is again less than 6291 from 500M of incremental - but it's getting close!

Let's try adding some length 8:

Up to 6: 15216 (200M, 93.73%)
7: 5736 (200M, 20.15%)
8: 1813 (100M, 1.08%)

That's 22765 total, which is a bit less than we had without length 8. After the 10G incremental, there are only 5913 of the above Shuffle's unique, which is getting even closer to but still less than 6291 from a further 500M of incremental.

I guess by adjusting the experiment parameters, I'd eventually find a set where Shuffle briefly outperforms incremental, but this would be unlikely in real-world usage without prior knowledge. Yet this may be another reasonable mode to run for a while after or along with lots of others.

To put all of these numbers in perspective, the `best-by-score` rules had cracked 3002693 out of 6969140 total unique hashes.

**Comment by solardiz** [comment]
Testing with our default `password.lst` against a 10M representative sample from HIBPv8 (6969140 unique NTLM hashes), after having excluded `password.lst` as-is and reversed (rule `r`), by length, for up to 10M candidates per length (bumped into this limit starting with length 6), dupe suppressor not enabled:

4 and below: 4523
5: 14098
6: 40314
7: 5398
8: 742
9: 490
10: 327
11: 0
12: 0

These are unique password counts. I did crack some length 11 with a longer run.

The current default length limit configurable in the external mode `init` is 10, but based on the above I recommend running separately with `--max-length=6`, `--length=7`, and `--min-length=8`. Those 3 runs limited to 10M candidates each crack:

Up to 6: 41867
7: 5398
8 to 10: 1058

or maybe it's better to split further:

Up to 5: 18621
6: 40314

After having excluded 100M candidates of `--rules=best-by-score` + 100M of `--rules-stack=best-by-score` (each ran to approx. 2% progress before hitting 100M):

Up to 5: 3056
6: 16748
7: 2655
8 to 10: 842

After having excluded all `--rules=best-by-score` (with the same `password.lst` as in all of these tests):

Up to 5: 423
6: 1748
7: 651
8 to 10: 439

Letting them run to up to 100M candidates each (49.25% through wordlist for length 6, 10.23% for 7, 0.18% for 8+):

Up to 5: 423
6: 9529
7: 3366
8 to 10: 780

separating length 8, 9, 10:

8: 1813 (1.08%)
9: 419 (0.38%)
10: 337 (0.18%)

Somehow the cumulative result for 8 to 10 in the first test (10M total) was better than for 8 alone, but after having excluded more rules-crackable passwords and upgrading to 100M per Shuffle run, it's worse than for 8 alone.

Up to 6: 9661 (48.37%) just to have it limited to 100M for a further comparison:

That's 9661+3366+1813+419+337=15596 for 500M. Instead of the Shuffle runs, continuing with `--rules=worse-by-score` for 500M candidates (dupe suppressor disabled) cracks 17695, so Shuffle is a little less effective than simply continuing with rules. It can be made more effective (per candidate) by limiting it to lower lengths. OTOH, further rules can be made more effective by running another ruleset rather than the known-worse portion from the same original/split ruleset. 500M of `--rules=OneRuleToRuleThemStill` (including dupes) cracks 26185. 500M of default `--incremental` cracks 81403 (and the unique cracked by Shuffle reduce to 10081). All of these 500M options were tried on their own, never one on top of another (except for the retroactive comparison of incremental significantly reducing Shuffle's unique).

For a further comparison, continuing the default `--incremental` for a second 500M cracks 36535 more, which is 3.6x more than Shuffle's unique by that point (after first 500M incremental). 500M Shuffle's remaining unique reduce to 8878 on top of the 1G of incremental. Letting it run for yet another 500M (for 1.5G incremental) adds another 27663, which is again much more than Shuffle's was, and leaves 7923 Shuffle unique.

Overall, not surprisingly Shuffle is less effective than the alternatives, but maybe it adds some unique cracks on top of other exhausted possibilities? Let's try 10G of incremental on top of the `best-by-score` rules baseline. This cracks 314521. A further 500M of incremental (10.5G total) cracks 6291. 500M Shuffle's remaining unique after 10G were 4741. So even after 10G Shuffle is still less effective than simply continuing with incremental, although if we compare against Shuffle limited to lower lengths it'd probably break even. Let's try, on top of our rules baseline:

Up to 6: 15216 (200M, 93.73%)
7: 7836 (300M, 29.86%)

That's 23052 total, which is on par with further rules (although those produce dupes, which we'd suppress when running against slower targets, for more unique candidates and thus cracked passwords total). It's still much lower than continuing with incremental after rules. After the 10G incremental, there are only 5483 of the above Shuffle's unique, which is again less than 6291 from 500M of incremental - but it's getting close!

Let's try adding some length 8:

Up to 6: 15216 (200M, 93.73%)
7: 5736 (200M, 20.15%)
8: 1813 (100M, 1.08%)

That's 22765 total, which is a bit less than we had without length 8. After the 10G incremental, there are only 5913 of the above Shuffle's unique, which is getting even closer to but still less than 6291 from a further 500M of incremental.

I guess by adjusting the experiment parameters, I'd eventually find a set where Shuffle briefly outperforms incremental, but this would be unlikely in real-world usage without prior knowledge. Yet this may be another reasonable mode to run for a while after or along with lots of others.

To put all of these numbers in perspective, the `best-by-score` rules had cracked 3004506 out of 6969140 total unique hashes.

**Comment by solardiz** [comment]
OK, after the rules (which crack 3002693) + 100G of incremental (which crack another 634495), any of the 500M of Shuffle add more cracks than another 500M of incremental:

First Shuffle 500M above (was 15596) has 2348 unique left on top of 100G incremental
Second 500M above (was 23052) has 1210 left
Third 500M above (was 22765) has 2107 left

Another 500M of incremental adds only 548

I guess this gain is very brief and wouldn't hold for much longer Shuffle runs (less common and longer input passwords), but it does indicate they can crack a bit more than other methods at some point.

**Comment by solardiz** [comment]
Announced to users in https://www.openwall.com/lists/john-users/2024/06/02/1
