### ISSUE TITLE
pdf2john.pl produces hash for unencrypted file

### ISSUE THREAD

**Issue by KSonny4** [openwall/john#4203]
Hi! I am using pdf2john.pl to obtain hash for PDFs. However I obtain hash even for the unencrypted PDF. Is it okay? And if so, why?

### Steps to reproduce ###

- Download [https://www.fsco.gov.on.ca/en/pensions/Forms/Documents/1294E.1.pdf](https://www.fsco.gov.on.ca/en/pensions/Forms/Documents/1294E.1.pdf)
- run `pdf2john.pl 1294E.1.pdf`
-  you obtain `$pdf$4*4*128*-1068*1*16*7368a13d60455d468c9088e17891bb11*32*31bf1311e94af253cb12758a674cb42900000000000000000000000000000000*32*ca2f918cc60da9eb2b955e10f81359be49cf9db50a7dc97e276185a74baa8acd` which is empty password.

### System configuration ###
Attach details about your OS and about JtR, including:
Version: 1.9.0-jumbo-1
Build: linux-gnu 64-bit x86_64 AVX AC OMP
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
GNU libc version: 2.27 (loaded: 2.27)
Crypto library: OpenSSL
OpenSSL library version: 01010100f
OpenSSL 1.1.1  11 Sep 2018
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by ghost** [comment]
> Is it okay? And if so, why?

These are reasonable questions. Unfortunately, the author of `pdf2john.pl` is not a JtR developer. Dhiru (a JtR dev) glued the pieces and added them to the JtR. So, it is unlikely you will get an answer.

That said, I would say it is not a bug, since:
* It generates a valid and crackable hash.
* The password is an empty string ("").
* It would be "just an Enter". A kind of "no password".
*******

If you are still unhappy, post a message at ` john-users` mailing list. Some user familiar with PDF encryption may be able to give you a better explanation.

Anyway, the issue will be keep opened.

**Comment by KSonny4** [comment]
For this exact PDF I posted above the password is not "an Enter" it's just opened by itself, that's what confuses me. Is the opening of a PDF with blank password some kind of feature that PDF viewers have?

**Comment by ghost** [comment]
>it's just opened by itself, that's what confuses me. Is the opening of a PDF with blank password some kind of feature that PDF viewers have?

It is NOT a regular PDF file. It is SECURED, as seen below.

![image](https://user-images.githubusercontent.com/1702923/74104019-824f4280-4b2f-11ea-88c1-8f6986d1be5b.png)

In fact, using Linux, until now I couldn't see the content [1] (I probably need to install Adobe Software).

[1] Evince, Google Viewer, FoxIt
