### ISSUE TITLE
Supported hash not being recognized no matter what is tried

### ISSUE THREAD

**Issue by onthaxian** [openwall/john#4224]
JtR supports vbulletin < 3.8.5 hashes with format types dyanmic_6 and dynamic_7 and dynamic_1007

The version of john I am using is john-1.9.0-jumbo-1-win64, latest version I could see for download.

I have a hash (modified so as not to paste real one, characters at end changed), like so:

50cff86a9fe4a2ccbc67e95272321dbe:_j&+jx^uzJ"S*gFn$k*s)&b=&0-~#7

I have tried using format="dyanmic_6", changing the colon to a percentage and specificying the percent sign as a field seperator, format="dynamic_7" and format="dynamic_1007".

I know that JtR supports this has type, yet every combination I try along with --show:invalid reports invalid hash.

With the colon changed to percent sign I have tried:
john hash.txt -format:"dynamic_1007" --show:invalid --field-separator-char="%"

john hash.txt -format:"dynamic_7" --show:invalid --field-separator-char="%"

And with the colon:

john hash.txt -format:"dynamic_6" --show:invalid

In all cases the result is:

50cff86a9fe4a2ccbc67e95272321dbe:_j&+jx^uzJ"S*gFn$k*s)&b=&0-~#7
0 valid hashes, 1 invalid hash

**Comment by ghost** [comment]
Isn't it a fixed 3 byte salt? E.g., this is a valid hash:
```
$dynamic_1007$50cff86a9fe4a2ccbc67e95272321dbe$+jx
```

I'm affraid you are using an incorrect hash for testing.

**Comment by ghost** [comment]
Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken.

We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:

- try to make your point clearer;
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).

**Comment by onthaxian** [comment]
Versions of vBulletin after 3.8.5 uses a fixed 30 byte salt.

I had tried a lot of searching before posting, and it seemed dynamic_1007 would still work. My hash is valid.

I apologize for this not being a proper bug report however, I had tried to search before posting and was certain I was doing everything correctly. I will post on the mailing list.

**Comment by magnumripper** [comment]
https://www.openwall.com/lists/john-users/2020/03/12/1
