### ISSUE TITLE
rar2john, 7z2john producing very long hashes

### ISSUE THREAD

**Issue by POMATu** [openwall/john#4237]
Hi,

So I have bunch or rar and 7z archives, but these utilities produce very long hashes (20938446 symbols) and I cant import them to hashcat. It happens always for these specific archives, other ones work fine.

What can be a cause of this problem? Does that mean that archives are broken or its some bug or new encryption format? Btw rar archive is basically $rar3, I doubt it is some new format.

Thanks

**Comment by ghost** [comment]
Some *2john tools output a large file. See #4051

That said, there's no indication of a bug in what you described. From above, it works to you.
****

From https://github.com/magnumripper/JohnTheRipper/issues/4050#issuecomment-513225206 
>> magnum, maybe we need to have zip2john and rar2john (any others?) output a message to stderr that it's normal for the resulting "hashes" to be very large? Maybe only output this when they're in fact very large. Otherwise people get confused, expecting "hashes" to be tiny.

Or, from john-users ML
>> The generated file will include a chunk of data from the zip (EDITED: 7zip also) file, 
of whatever size is required for cracking. Unfortunately it's 
hex-encoded which means a 5 MB data chunk will end up as 10 MB worth of 
hex digits.

**Comment by magnumripper** [comment]
What he said. John can load arbitrarily large input files but hashcat currently can't. You should probably ask them about that, not us!

Some of the archive tools (rar2john for one) try to pick the smallest usable file from an archive, when applicable. So from some large archives you'll get a very small file for the cracker. From some other archives that's simply not possible (eg. one single huge file in the archive) and because we hex-encode the data (for legacy reasons) it may actually end up twice as large as the archive you want to crack. That's kinda silly but it is what we've got right now.

**Comment by ghost** [comment]
Indeed. Sorry, Pomato. Anyway, this is a support question.

**Comment by POMATu** [comment]
Ok now its clear, I will switch from hashcat to johntheripper, Thanks
