### ISSUE TITLE
Bitcoin2John is not giving any hash

### ISSUE THREAD

**Issue by DamskaySteve** [openwall/john#4247]
Hello,

I think Bitcoin2John is not working and there is a bug on it. When I execute the command on my wallet.dat by doing:

- py bitcoin2john.py wallet.dat

And it does not give any Hash while my wallet.dat exists well and has no problem.
Problem image: https://i.imgur.com/wgKc9fm.png
![wgKc9fm](https://user-images.githubusercontent.com/37937235/78564647-0e72a300-781d-11ea-8e04-2f285619affd.png)

Can you help me?

**Comment by ghost** [comment]
Can you please try to run this file (I added a couple of prints to it).
[bitcoin2john.zip](https://github.com/magnumripper/JohnTheRipper/files/4438937/bitcoin2john.zip)

I don't see how the committed script couldn't do anything (without errors and hash).

**Comment by solardiz** [comment]
@DamskaySteve `bitcoin2john.py` as currently found in this repo works fine as recently confirmed e.g. on issue #4225. Like @claudioandre-br, I also don't see how it (nor even an older revision of it) can just terminate and print nothing, not even an error message. There's probably something wrong in your setup. For example, can you show us the sizes of those two files - the script and the wallet - like the output of `dir`? Please copy-paste text from the terminal window instead of using a screenshot, so that the complete information is available right here.

**Comment by solardiz** [comment]
With no further info, I assume this was some undetermined user error. Closing the issue.
