### ISSUE TITLE
#Building warnings: libz (pkzip and some other formats) ........ no, Why pkzip is disabled? Is this normal?

### ISSUE THREAD

**Issue by BarrowHill** [openwall/john#4266]
Sorry for question, but could you please answer me, when building on Windows with
./configure && make -s clean && make -sj4  as mentioned in install-windows.
_______
......
Optional libraries/features found:
libz (pkzip and some other formats) ........ no

Install missing libraries to get any needed features that were omitted.

electrum_fmt_plug.c:509:2: warning: #warning "zlib missing, Electrum formats not built" [-Wcpp]
pkzip_fmt_plug.c:1759:2: warning: #warning pkzip format requires zlib to function. The format has been disabled [-Wcpp]

Securing executables.
Warning: setting dynbase on file with no relocation info (../run/john.exe).
.....
Make process completed.
__________
Why pkzip is disabled?
all these warning are normal?
After these warnings will all zip, rar and ETH wallet functions work correctly?

### System configuration ###
Windows 10 x64, cygwin64
git clone latest release

**Comment by solardiz** [comment]
For user support questions, please use the john-users mailing list.

These warnings are sort of normal, but they mean what they say. To avoid them, install zlib (a Cygwin (sub)package; sorry, I don't recall what exactly it's called in Cygwin, but should be easy to spot). You can also simply use our Windows builds of JtR, instead of making your own.

After these warnings, pkzip and Electrum formats won't work. The rest should.
