### ISSUE TITLE
Fix and enhance our AES-NI support

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4314]
I was surprised to find our KeePass-opencl format perform about twice faster on CPU with Intel's OpenCL than our CPU format does. Turns out we don't have SIMD support in the CPU format. We should probably add that.

**Comment by magnumripper** [comment]
The heavy lifting (unless Argon2) is AES-encryption of between 192 KiB to 1 GiB or more (a 32 byte block over and over again, eg. 32 million rounds or more). AES-NI is already used, not sure if we can make it better.

**Comment by solardiz** [comment]
Oh, I didn't realize it's just AES in the loop. But no, we don't seem to use AES-NI there. When I interrupt a benchmark of this format in gdb, I see it run non-AES-NI code in OpenSSL's `AES_encrypt`.

We could probably speed this up by actually using AES-NI. And speed it up some more by interleaving multiple instances.

**Comment by solardiz** [comment]
I guess to use AES-NI via OpenSSL we need to use EVP.

We also have AES-NI asm code in our tree `src/aes/aesni`, but we don't seem to compile it? Edit: looks like it needs `yasm` installed. And then we'd need to maintain it, such as to add support for VAES instructions.

Also, the speedup I had observed with OpenCL suggests that for CPUs without AES-NI we could reasonably have a SIMD (edit: perhaps bitslice) implementation of AES (computing multiple instances at a time). But we may not want to bother.

**Comment by solardiz** [comment]
Tried installing `yasm`, got:

```
AES-NI support ..................................... run-time detection
```

but benchmarking this format, it still runs the non-AES-NI code in OpenSSL, at same old speed. Also, I don't see any AES-NI instructions in `john`.

**Comment by magnumripper** [comment]
We did use EVP prior to the introduction of our `src/aes/aesni` stuff. I haven't cared about the latter for years or even verified I got the "run-time detection", perhaps time for a rehaul.

**Comment by magnumripper** [comment]
I guess our fallback to OpenSSL should include EVP, as opposed to changing anything in format code. Somehow I never got this idea before but it would certainly be cleaner.

**Comment by magnumripper** [comment]
Note to self: Our current AES-NI code (that requires yasm) was introduced in 3768ed7d4 by Harrison Neal (@hantwister). That was before even our autoconf stuff, and plugins I think.

**Comment by magnumripper** [comment]
Several issues here. The first one is this test in src/aes/Makefile.in
```
GCCV44 := $(shell expr `$(CC) -dumpversion` \>= 4.4)
```
This explains why it suddenly stopped working some time ago: The problem is `>=` is alphabetical as opposed to numerical, so version 10 and above are considered lower than 4.4 and disabling AES-NI (the 4.4 test is presumably for some compatibility reason). For numerical comparisons only integers are supported (we'd need to test for >= 5) so I intend to use this fairly nice workaround (the best I found, after rejecting tons of contraptions using crazy stuff including but not limited to sed and awk):
```
GCCV44 := $(shell echo `$(CC) -dumpversion` \>= 4.4 | bc)
```

But there are more problems: With the above fixed, the o5logon format gets a speedup (of 2x, so pretty substantial). That format explicitly use the functions in our AES wrappers. But NO other format gets the AES-NI stuff. I was always convinced that any format that includes `"aes.h"` as opposed to `<openssl/aes.h>` would automagically use the wrappers correctly and get AES-NI where supported - but right now I'm not sure that was ever the case. It certainly isn't now.

Finally, there's this comment in aes/aes.c and aes/aes_func.h:
_NOTE: These functions are intended to be used by algorithms that continuously switch out AES keys - with each computation, state is built, used and torn down. Consider using straight OpenSSL EVP methods if your algorithm would do a lot of work with any single key._

While I believe nearly all formats fall into the former category, KeePass doesn't - so it probably needs EVP (or a better/more complete implementation of our code) regardless.

So TLDR; here's my current plan:
1. Fix the wrappers so indeed any code that `#include "aes.h"` does get the wrappers with NO other changes (using eg. `AES_encrypt()`). I'm assuming this is possible and not too hard.
2. For the non-AES-NI case, fall back to OpenSSL with EVP if available, and as a last resort the vanilla AES that's under our aes directory.
3. For KeePass (and maybe one or a few other formats?), add code within the format that use EVP if available, and the AES-NI wrappers if not. OTOH a better solution is likely to rewrite our AES-NI code to be fast for the "do a lot of work with any single key" case.
4. If possible, I'd also like to get rid of the need for yasm. I assume the assembler code can be "translated" to something gcc understands.
5. While at it, add a line in `--list=build-info` that shows whether AES-NI will be used or not.

**Comment by magnumripper** [comment]
Oh, and
6. Have a look at adding VAES.

**Comment by magnumripper** [comment]
I just confirmed KeePass CPU format gets a 12x boost (for AES KDF) using OpenSSL EVP.

**Comment by solardiz** [comment]
> This explains why it suddenly stopped working some time ago: The problem is `>=` is alphabetical as opposed to numerical, so version 10 and above are considered lower than 4.4 and disabling AES-NI

This tells us that we haven't been using `relbench` enough, or we'd notice a performance regression in many formats when going from gcc 9 to 10. Edit: Oh, perhaps only on systems with `yasm`, which narrows it down a lot.

> (the 4.4 test is presumably for some compatibility reason).

I suspect that `binutils` version could be more relevant.

> If possible, I'd also like to get rid of the need for yasm. I assume the assembler code can be "translated" to something gcc understands.

Right. I think most systems where our code is getting built don't have `yasm` installed. There's Intel syntax mode in GNU `as` (IIRC, available via `.intel` or such), so the changes to get this to work may not be too extensive. That said, it may be best to ditch this old code and find or write something new, which would also have newer CPUs/VAES/interleaving in mind.

**Comment by solardiz** [comment]
> > (the 4.4 test is presumably for some compatibility reason).
> 
> I suspect that `binutils` version could be more relevant.

Or maybe not. I thought of `binutils` since it provides `as`, but this code uses `yasm` anyway.
I don't see any obvious dependency on GCC 4.4+ in the original commit from 2014, yet this check was already in there. The code uses `__attribute__ ((aligned (16)))`, but per our check in `common.h` this was already available in 2.7+.

**Comment by magnumripper** [comment]
Even better, I guess, would be C source for AES optionally using intrinsics for AES-NI, VAES and possibly also ARM and whatever else there is. I tried searching for such code (or assembler) but it's surprisingly hard to find.

**Comment by magnumripper** [comment]
https://github.com/Mbed-TLS/ might be a contender

Edit: Tried using mbedTLS (as a lib) for the heavy AES loop in KeePass format, and indeed it's 13.6x as fast as vanilla code. The EVP version was 12.6x so mbedTLS is 7.7% faster than that.

BTW figures are on my "8-Core Intel Core i9" 2.4GHz macbook 2019, macOS doesn't show me any better spec on what exact CPU that means.

**Comment by solardiz** [comment]
Yes, I am leaning towards intrinsics too - and I thought it'd be our own, because we're unlikely to find pre-existing code with multi-input/output API for interleaving. But we can start with something simpler, like what you found.

**Comment by magnumripper** [comment]
So new, much simpler plan:
1. Replace our src/aes subdirectory with one that holds stuff nicked from mbedTLS.
2. Modify src/aes.h so only that one needs to be included, and make abstraction macros in it, so format code don't need any changes.

The mbedTLS code also has "AES acceleration on Armv8-A processors with the Armv8-A Cryptographic Extension".
