### ISSUE TITLE
External mode cipher_limit is not set correctly

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4367]
Unless the `--max-length` option is given, `cipher_limit` is set to 125 and not to the format's maximum length. Among other effects, this results in a segfault with `phpass` and `phpass-opencl` formats when trying to use `--external=Repeats` on them.

**Comment by magnumripper** [comment]
Ouch. Seems to be introduced in 6ba42b308f in Feb 2018. Total brainfart by your's truly and would likely have been spotted by a peer review.

**Comment by magnumripper** [comment]
After digging into it I think it was actually fine at/after 6ba42b3, things have moved around since. Not sure where bugs were introduced but never mind.

PR inbound. The problem now was that `ext_init()` relies on `options.eff_maxlength` having been set - but it wasn't yet. Also, for `--stdout=N` the second call to `ext_init()` for updating lengths was never made at all. While at it I fixed a minor bug that resulted in Unicode external modes suffering from not knowing `cipher_limit` *in bytes* where they consider length options being given in *characters*.
