### ISSUE TITLE
brew install john-jumbo doesn't work

### ISSUE THREAD

**Issue by ghost** [openwall/john#4412]
I runned brew install john-jumbo and this happens

**Error: Failure while executing; `cp -pR /var/folders/_2/yjdt005107v9ng154y7bdqtw0000gq/T/d20201022-28208-1kkr4f0/john-jumbo/. /usr/local/Cellar/john-jumbo` exited with 1. Here's the output:
cp: /var/folders/_2/yjdt005107v9ng154y7bdqtw0000gq/T/d20201022-28208-1kkr4f0/john-jumbo/./1.9.0/share/john/john: Permission denied**

then after:

**Warning: Bottle installation failed: building from source.
==> Patching
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/Patrick/Library/Caches/Homebrew/downloads/fc0fb54eb1fa3fbdeee5e66657a359b92fb70ef353363d810b02f25e0dfe4bb8--a537bbca37c1c2452ffcfccea6d2366447ec05c2.patch**

I also did brew install john but john did not work so I uninstalled it. How do I fix this problem?

**Comment by magnumripper** [comment]
It looks to me you have a basic problem with Homebrew in general. Try something like `brew doctor` to start with.

If that doesn't give you any clues: From the little I see here I would expect it to be a bug in Homebrew and that means you should report this to Homebrew instead of us.

Please report back.

**Comment by ghost** [comment]
> It looks to me you have a basic problem with Homebrew in general. Try something like `brew doctor` to start with.
> 
> If that doesn't give you any clues: From the little I see here I would expect it to be a bug in Homebrew and that means you should report this to Homebrew instead of us.
> 
> Please report back.

So I ran brew doctor and I had a bunch of alerts, I fixed them all and now it says "Your system is ready to brew". I ran brew install john-jumbo and it comes up with the same alerts. Still, thank you for you're help.

**Comment by solardiz** [comment]
@hash-glitch This is an issue specific to either the Homebrew packaging of JtR or to your system. Either way, we can't do anything about it - we're upstream developers of JtR not involved in its Homebrew packaging - so I'll close the issue now. That said, it is useful for us to know whether there's a problem with the packaging, so if you do contact Homebrew about this or otherwise figure it out, please post an update to this issue (which you can do despite of it being closed). Thanks!

I'm not a Mac user, but from common sense this looks to me like a corrupted setup of Homebrew or its cache. This could have happened e.g. if you ran out of free disk space for a moment, or for many other reasons. I'd try clearing out everything Homebrew related and starting fresh (maybe reinstall it, if you don't have too many other packages installed with it that you need).

**Comment by dinvlad** [comment]
Check if it's somehow blocked by your anti-virus. It might be detected by some, like SentinelOne. If it is, then recompile from scratch perhaps.
