### ISSUE TITLE
zip2john calculate wrong hash

### ISSUE THREAD

**Issue by memfissoftware** [openwall/john#4418]
Hello,

I try to calculate hash with zip2john but it calculates very weird has for a encrypted zip file.

[tahlil.zip](https://github.com/openwall/john/files/5449196/tahlil.zip)
[hash.txt](https://github.com/openwall/john/files/5449199/hash.txt)

i also attached zip and hash file.
im pretty sure the files in the zip file were encrypted by same password.

**Comment by ghost** [comment]
John recognizes and it can load the hash. It is not "weird". If you have a hint about the password, we can check if the zip file is crack-able. 

I can say everything is happening as expected.

```
$ cat ~/hash.txt | tail -c 100
83312c8904bf5445739287a1db1b*9a95363fa47e1dbcc3f2*$/zip2$:TestSonucRaporu.pdf:tahlil.zip:tahlil.zip
```
```
$ ../run/john --format=opencl --fork=3 --session=2 -dev=5 ~/hash.txt --word=/home/claudio/rockyou.txt --rules
Using default input encoding: UTF-8
Loaded 2 password hashes with 2 different salts (ZIP-opencl, WinZip [PBKDF2-SHA1 OpenCL])
Node numbers 1-3 of 3 (fork)
Device 5: GeForce GTX TITAN X
Device 5: GeForce GTX TITAN X
Device 5: GeForce GTX TITAN X
2: LWS=512 GWS=49152 (96 blocks) 
3: LWS=32 GWS=98304 (3072 blocks) 
1: LWS=32 GWS=786432 (24576 blocks) 
Each node loaded 1/3 of wordfile to memory (about 44 MB/node)
```

****
Although this issue is worded as a bug report, not as a question, I'm afraid you're mistaken.

We assume you are genuinely thinking you are reporting a real bug to help the project. That said, please:

- confirm you are using the updated bleeding-jumbo source code (not a numbered release, as this GitHub issue tracker is for issues still present in our latest code, not only in the releases we had made earlier);
- ensure that you ran a `./configure && make -s clean && make -sj8`;
- try to make your point clearer;
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).

**Comment by magnumripper** [comment]
> im pretty sure the files in the zip file were encrypted by same password.

Perhaps what's confusing you is the fact two hashes are produced despite you think they share the same password? There's no way for the tools to know whether both files use the same or different passwords, so a hash line for each file was produced*. As they have different salts this will slow down cracking by (in this case) half so a good method for attacking it would be to target just one of the files and if/when it cracks, just verify that the other one has the same.

*) This behavior currently isn't consistent among our tools. For example, `rar2john` will pick the smallest (usable) file automagically for RAR v3 and there isn't even an option to change that. And that's not even consistent with the same tool's behavior for RAR v5, which is to dump all files (although they use to share salt so that's more logical).

Perhaps we should make all similar tools act similar and also using consistent options for dumping a specific file or all files.
