### ISSUE TITLE
Multi-line status output, delayed status, perhaps delayed exit?

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4449]
#4444 adds pressing 'd' for delayed status (it will print once all salts are processed for current batch).

As discussed we could also want (and I have experimental code for) a more detailed multi-line status output. For example, listing all options used, saying things like `Salt: 12/34, Rule: 56/78` and possibly many more things (which would you want?).

My current code has 'd' for delayed, and 's' for detailed status. Another possibility is 'd' for detailed and perhaps 'D' for delayed. Would we ever want a delayed AND detailed status?

Someone once asked for a "delayed exit" as well, aborting session once current batch is finished. Hashcat has that (as 'c' for checkpoint).

**Comment by solardiz** [comment]
I think we should add reporting of instantaneous speeds (as well as ETA based on them) rather than only the long-term averages that we currently report. Here "instantaneous" can mean e.g. over last one minute or over last batch of candidates. We could include them in the multi-line status or simply display our current status line but using instantaneous speeds on a magic keypress like `i`.

> Someone once asked for a "delayed exit" as well, aborting session once current batch is finished. Hashcat has that (as 'c' for checkpoint).

I think hashcat ideally needs to finish the current batch of candidates because it doesn't(?) have what we call "salt restore". Our `q` is actually delayed exactly to the extent needed not to lose any work on restore, and that's generally sufficient. It'd take some obscure use case to want a full batch of candidates finished when interrupting a session.

**Comment by solardiz** [comment]
Detailed multi-line status was added as part of #5046 in 677633d4608e9e065bb298c925ce0199876ff04d. magnum has listed more ideas for what to include in multi-line status, but I think we don't need to keep this issue open for those.
