### ISSUE TITLE
human_prefix_small() precision loss

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4533]
As mentioned in https://github.com/openwall/john/pull/4524#discussion_r546287925:

This got me looking inside `human_prefix_small()`, and it's really weird. It might bring num to just above 1.0, then round it to integer 1 - that's very little precision left. We need to fix it.

**Comment by magnumripper** [comment]
IIRC I do have a pending fix for it already, I just stalled completely for a while doing other things.

**Comment by magnumripper** [comment]
```diff
diff --git a/src/misc.c b/src/misc.c
index d382f7aee..c9d169612 100644
--- a/src/misc.c
+++ b/src/misc.c
@@ -587,15 +587,15 @@ char *human_prefix_small(double num)
 	char prefixes[] = "\0munp";
 	char *p = prefixes;
 
-	while (p[1] && num > 0 && num < 1) {
+	while (p[1] && num > 0 && num < 0.9995) {
 		num *= 1000;
 		p++;
 	}
 
 	if (*p)
-		snprintf(out, 16, "%u %c", (uint32_t)num, *p);
+		snprintf(out, 16, "%.0f %c", num, *p);
 	else
-		snprintf(out, 16, "%u ", (uint32_t)num);
+		snprintf(out, 16, "%.0f ", num);
 
 	return out;
 }
```
Is this any better? I'm not quite sure what edge cases to handle. The current use of the function doesn't see such edge cases but we should of course handle them.

**Comment by solardiz** [comment]
> Is this any better?

I think no. The issue wasn't an edge case. The issue was low precision in a fairly wide range. I think we need to write a program that would use this function to print a variety of numbers, which will make the issue apparent and allow for testing of fixes.

**Comment by magnumripper** [comment]
Well we could limit the scaling much like we do with the status c/s figures, such as "12314K p/s" instead of "12M p/s". In this case that would mean "12314 us" or "12.314 ms" instead of "12 ms".

For the current use case I prefer the latter though: Once we're in millisecond range I don't care about microseconds. Then again, printing "12 ms" for an input of 0.012999999 seconds (like the current code would) is obviously suboptimal - but that *is* an edge case and something like the diff above (even only the format change) would mitigate it. And frankly I don't even care whether it would say 12 or 13, it's just fine. Perhaps it's just a matter of documenting the function's flaws.

**Comment by solardiz** [comment]
> frankly I don't even care whether it would say 12 or 13, it's just fine

What if it says just 1 in place of 1.49? I thought a reporting that's off by 50% would be bad, and we'd rather see e.g. "1490 us" or "1.49 ms".
