### ISSUE TITLE
Amnesic -stdout piping

### ISSUE THREAD

**Issue by e2002e** [openwall/john#4588]
Hi, issue is when piping words with the options -stdout
When out puting lines on the console it does restore correctly.
When sending these words to another software, -restore option is ineffective.

./john -inc -stdout |../thc-hydra/hydra -l admin -x +1000 ssh://127.0.0.1 (Yes I'm making some add for my fork of hydra)
./john -restore |../thc-hydra/hydra -l admin -x +1000 ssh://127.0.0.1 -> Same words.

Piping to 'less' has the same issue.

**Comment by magnumripper** [comment]
First, try decreasing the `Save = 60` in john.conf to just `Save = 1` and see if it helps at all. It might. 

There are always some caveats with piping and abort/resume:
- OS buffers may fool John into restoring too late: Words that was sent into the pipe might not have been processed by hydra yet and we can't know that. This is not the problem here though.
- If John gets a "nice kill" it should save its session properly at end. If it was killed brutally enough not to, we rely on that john.conf `Save` setting having triggered a fairly recent session save.
- There's a thing we call "fix state" and I guess #4519 might have made things very slightly worse in cases like this (trading restore precision for speed).
- Finally, some modes can restore at virtually any point in the keyspace while others are much more imprecise.

This seem to work for me (even with original Save time):
```
$ ./john -inc -stdout -ses:test -max-cand=50000 | grep -n ^1234
$ ./john -res:test | grep -n ^1234
```
The output shows that it does resume a little early, but certainly not from scratch.

**Comment by solardiz** [comment]
Hi @e2002e. The combination of `--stdout` and eventual session restore is inherently unreliable. (Maybe we should disallow it altogether, although it's sometimes useful as a best-effort.) This is because piping involves buffering by the operating system and by the target program, which the `john` process doing `--stdout` and needing to update `.rec` files has no insight into. So it may end up writing into its `.rec` file that it has already reached a certain point, and thus a restore would start from that point, whereas the target program has not yet received/processed all of those candidate passwords. As a result, some of them will be skipped (never tested), leading to false negatives (some weak passwords not cracked).

(I was going to write more on the specific/different issue seen here, but magnum beat me to it. So posting what I already wrote in case saying it in these other words clarifies anything.)

**Comment by magnumripper** [comment]
> Maybe we should disallow it altogether, although it's sometimes useful as a best-effort

It would be a pity to disallow it. We could mention these issues in `doc/OPTIONS` - it doesn't seem to be mentioned at all.

**Comment by e2002e** [comment]
Ok I got it.
I will try editing john.conf.
See you.

**Comment by solardiz** [comment]
> It would be a pity to disallow it. We could mention these issues in `doc/OPTIONS` - it doesn't seem to be mentioned at all.

Right, or/and we could print a warning when `--restore` is used and `--stdout` is seen in the `.rec` file.

**Comment by e2002e** [comment]
Maybe you could make it ignore system buffers: "I sent x words, I'm
restoring at x+1". As an option. John knows how much word he's treated even
though unaware of the rest, right ?

Le jeu. 4 mars 2021 à 11:33, Solar Designer <notifications@github.com> a
écrit :

**Comment by magnumripper** [comment]
No, we just send words into the pipe (actually we just send them to stdout, without knowing whether there's a pipe there or not) and the rest is unknown: We have no idea (we can't know) whether things are buffered at all, how large the buffers might be, or how much of the buffer was eaten or not by the receiving program. I guess we could set stdout to be unbuffered (if we don't already) but that wont help much, if at all - we simply have no knowledge of the receiving end.

**Comment by magnumripper** [comment]
FWIW some people have experimented with using a FIFO in between. This can help *or make things even worse* but you could experiment with it for phun.

Example:
```
$ mkfifo fifo
$ ./john -inc -stdout > fifo &
$ ../thc-hydra/hydra < fifo -l admin -x +1000 ssh://127.0.0.1
```
(I had problems now trying the above, not sure what I'm missing. John exits fairly early)

**Comment by e2002e** [comment]
So the receiving program must buffer the data ? Recovery works 100% with >
(redirection). In the case of my generator which has a gui and outputs to
the console, I can start the program with a pipe to sort -u |wc and it'll
yield the correct count no matter how many times I stop it untill the end.
Reading on the flight is what I am doing with hydra. Do you think that when
reading the input into a file with a fixed size will solve my issue ?

**Comment by magnumripper** [comment]
> So the receiving program must buffer the data ?

No, I'm saying it might and we do not know: When we're in stdout mode, we *may* have a program (or several) in the other end of a pipe (or several pipes) *or* a file, or just a terminal screen. We just don't know. And if it is a program or several, it/they may buffer data or not - we can't know. So we can't adapt to the situation because we do not know what the situation is (well we do know whether the output is a terminal or not, but only that).

> Do you think that when reading the input into a file with a fixed size will solve my issue ?

Writing to a file and then letting Hydra read it should solve this problem but may introduce other ones, such as that file becoming too large for your disk.

I guess you could do something like this though:
```
# Do first 10,000 of them
$ ./john -inc -stdout -max-cand=10000 | ../thc-hydra/hydra -l admin -x +1000 ssh://127.0.0.1
# Do next 10,000
$ ./john -restore | ../thc-hydra/hydra -l admin -x +1000 ssh://127.0.0.1
```
Note though that one problem remains with `-max-cand`, namely that depending on what mode you're running (incremental in this case) it might resume suboptimally: When you resume it might repeat some of the last 10,000 words and just produce, say, 9,600 new ones. Some modes will resume right at the spot, some (like PRINCE) may have to repeat (I think) tens of thousands of words in some cases. So the larger max-cand value, the better, in general.

Disregarding that issue, you can then loop the resume some way, like
```
# Do first 10,000 of them
$ ./john -inc -stdout -max-cand=10000 | ../thc-hydra/hydra -l admin -x +1000 ssh://127.0.0.1
# Loop 10,000 words at a time until manually stopped
$ while true; do ./john -restore | ../thc-hydra/hydra -l admin -x +1000 ssh://127.0.0.1 ; done
```
