### ISSUE TITLE
FPGAs other than ZTEX 1.15y not supported

### ISSUE THREAD

**Issue by byposeidon** [openwall/john#4717]
Because the application supports 1 fpga card that is not in the market. 
https://www.ztex.de/usb-fpga-1/usb-fpga-1.15y.e.html
"USB-FPGA Modules 1.15y are deprecated."

Do you have suggestions for fast BCRYPT hash decrypting?

**Comment by ghost** [comment]
See also #4019 #4526 #4648

Basically, JtR needs sponsors and/or contributors.

**Comment by byposeidon** [comment]
We would be a sponsor. Is there anyone to contributor?
I think there is a compatibility problem with other fpga cards.

**Comment by solardiz** [comment]
> Do you have suggestions for fast BCRYPT hash decrypting?

If you manage to find used ZTEX 1.15y boards, then that's the best choice for bcrypt. (And we don't call it decrypting.)

> We would be a sponsor. Is there anyone to contributor?

Please e-mail me at solar@openwall.com to discuss your business need for this functionality and the amount of your possible sponsorship.

> I think there is a compatibility problem with other fpga cards.

We definitely don't support ZTEX 2.x cards, and we don't intend to support them - not even with sponsorship - because this isn't expected to be cost-effective. Used ZTEX 1.15y were at a much better price/performance ratio when we decided to target them. ZTEX 2.x are costlier and slower.

We might support more up-to-date and much larger FPGA boards from other vendors, but this would be a major project needing appropriate funding - it is not just an update of the existing functionality.

Meanwhile, I'll close this issue as it isn't something we need to track.

**Comment by solardiz** [comment]
One more detail: this project would also require an appropriate timeframe - at least several months, possibly a year - so it isn't something we can provide in response to an immediate and short-term business need. I feel I have to mention this detail because of some past discussions we had with prospective sponsors - they needed the functionality "now" and were not interested in funding a project to have this "a year later". This is reasonable, but it's part of what prevented the project from happening so far. I suspect it's probably the same in your case, so I expect this is a no-go. But if I'm wrong, then we have something to discuss.
