### ISSUE TITLE
Pause file status update

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4746]
From recent private conversation:
> Looks like we force printing of status line along with "Pause file seen", but not with "Pause file removed" - we probably should.

Also, some odd log file timestamp was seen when Pause file removed, only the first time?!

**Comment by magnumripper** [comment]
The odd time stamp is caused by this
```c
		if (john_main_process)
			fprintf(stderr, "Pause file removed, continuing\n");
		log_event("Pause file removed, continuing");

		/* Disregard pause time for stats */
#if !HAVE_SYS_TIMES_H
		end = clock();
#else
		end = times(&buf);
#endif
		status.start_time -= (start - end);
```
If we call `log_event()` after "fixing" the time, it should be gone. OTOH @solardiz would you prefer us to not hack the time? There are pros and cons. I think I prefer keeping it, but moving the `log_event()`. That will make it "look" (performance and time wise) like the session was actually aborted and later resumed.

**Comment by magnumripper** [comment]
Here's a proposed fix then
```diff
diff --git a/src/cracker.c b/src/cracker.c
index 2fcd81314..ad568d727 100644
--- a/src/cracker.c
+++ b/src/cracker.c
@@ -744,7 +743,6 @@ static void crk_poll_files(void)
 
                if (john_main_process)
                        fprintf(stderr, "Pause file removed, continuing\n");
-               log_event("Pause file removed, continuing");
 
                /* Disregard pause time for stats */
 #if !HAVE_SYS_TIMES_H
@@ -753,6 +751,9 @@ static void crk_poll_files(void)
                end = times(&buf);
 #endif
                status.start_time -= (start - end);
+
+               log_event("Pause file removed, continuing");
+               status_print();
        }
 }
 
```
However, if we do keep the "time hack", there's not much point in the second status print - it should be very close to the one printed before sleeping. If we drop the time hack, it makes more sense: We'll get to see how much it hurt us.

**Comment by magnumripper** [comment]
> OTOH @solardiz would you prefer us to not hack the time? 

BTW, I usually have `LogDateFormat` set in john.conf, rendering wall-clock timestamps in the log file as well, so I'd see how long we actually paused anyway. With the hack in place, you'll never know otherwise.

**Comment by magnumripper** [comment]
On a side note, it's a pity I'm pausing **all** the jobs on super just to test something on device 1. We could consider using something like `pause.1` for pausing only node 1 (while still allowing `pause` to pause all jobs). OTOH it's kind of bloat and this isn't a very common problem.

**Comment by solardiz** [comment]
I didn't realize we had the hack to exclude the pause time. When I suggested printing the status, I was hoping it'd let the user figure out the pause duration (difference between the two status lines), but with this hack this wouldn't be the case. So can we maybe include the pause duration explicitly in the "continuing" message? And it's fine to keep the hack, then.

However, I'd replace this:

```c
		status.start_time -= (start - end);
```

with:

```c
		status.start_time += end - start;
```

which I think is equivalent, but more descriptive of what we're actually doing, right?

Also, in our default `john.conf` we should probably comment out the `AbortFile` and `PauseFIle` lines, and edit the comments accordingly (so that the user knows those are not defaults, but are commented out examples that need to be explicitly enabled for them to work). Otherwise, I guess we currently incur performance overhead even when the user didn't intend to use this feature, right?

Per-device pause files could be nice, but probably not worth the complexity. Maybe instead we need a way to override `john.conf` settings from the command-line (and thus from `.rec` files, too) - then it would be convenient to have different `PauseFile` settings in different sessions.

**Comment by magnumripper** [comment]
> Also, in our default `john.conf` we should probably comment out the `AbortFile` and `PauseFIle` lines, and edit the comments accordingly (so that the user knows those are not defaults, but are commented out examples that need to be explicitly enabled for them to work). Otherwise, I guess we currently incur performance overhead even when the user didn't intend to use this feature, right?

Good point. I did so now, but we might want to revisit it: IIRC we stopped having commented-out stuff in the config because tools like Johnny can ask for all possible parameters (eg. with `../run/john --list=parameters:options`) and commented-out ones will obviously not be listed. Maybe we should have it uncommented but set to an empty string (if that works and solves the problem).
