### ISSUE TITLE
Could not connect to any X display.

### ISSUE THREAD

**Issue by altjx** [openwall/john#4815]
I have performed the following steps, per the documentation:

```
====================
Debian based distros
====================

These steps apply to all the Debian (included) based flavors such as Ubuntu,
Mint etc.

1) sudo apt-get install g++ git qtbase5-dev
2) git clone https://github.com/shinnok/johnny.git && cd johnny
3) git checkout v2.2 # switch to the desired version
4) export QT_SELECT=qt5
5) qmake && make -j$(nproc)
6) ./johnny
```

For some reason, I'm unable to actually run `johnny` due to not having an X Display. I'm doing this over a GPU instance in EC2, so not quite sure what I need to change here or if I'm doing something incorrectly. See example below:

```
ubuntu@ip-172-31-9-198:~/johnny$ ls
CHANGELOG    Makefile                    hashtypechecker.o  johnny         main.o                            moc_hashsortfilterproxymodel.o  moc_johnattack.o     moc_johnprocess.o   moc_menu.o                         moc_passwordfilemodel.o  moc_textlabel.cpp            qrc_resources.cpp  tabwidget.o   ui_aboutwidget.h
DEVELOPMENT  README                      installer          johnny.pro     mainwindow.o                      moc_hashtypechecker.cpp         moc_johnhandler.cpp  moc_mainwindow.cpp  moc_openotherformatfiledialog.cpp  moc_predefs.h            moc_textlabel.o              qrc_resources.o    textlabel.o   ui_mainwindow.h
INSTALL      forms                       johnattack.o       johnprocess.o  menu.o                            moc_hashtypechecker.o           moc_johnhandler.o    moc_mainwindow.o    moc_openotherformatfiledialog.o    moc_tabwidget.cpp        openotherformatfiledialog.o  resources          translations  ui_openotherformatfiledialog.h
LICENSE      hashsortfilterproxymodel.o  johnhandler.o      johnsession.o  moc_hashsortfilterproxymodel.cpp  moc_johnattack.cpp              moc_johnprocess.cpp  moc_menu.cpp        moc_passwordfilemodel.cpp          moc_tabwidget.o          passwordfilemodel.o          src                translator.o
ubuntu@ip-172-31-9-198:~/johnny$ export QT_SELECT=5
ubuntu@ip-172-31-9-198:~/johnny$ qmake && make -j$(nproc)
make: Nothing to be done for 'first'.
ubuntu@ip-172-31-9-198:~/johnny$ ./johnny -h
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
ubuntu@ip-172-31-9-198:~/johnny$
```

Any help or advice on what I'm doing wrong (or missing) would be greatly appreciated.

**Comment by ghost** [comment]
> For some reason, I'm unable to actually run johnny due to not having an X Display. 

Since johnny is a GUI, you need an X server (or a replacement like Wayland). However, this repository hosts the CLI only (`john`) cracking tool ~packages~.

Well, I recommend you just use the CLI: you are using a remote environment, it seems more straightforward to just use the command line. Yes, you can use a GUI remotely with EC2, even with Session Manager (so, it is up to you):
- you **DO NOT** need `johnny` to use John the Ripper with our without GPUs.
- remotely, via e.g. EC2, a CLI is more straightforward.
- you CAN use `johnny` in EC2 if you prefer to do so.

@solardiz, where should @altjx get help with johnny?

**Comment by ghost** [comment]
Sorry, I read `john-packages`. Anyway, the previous post is still correct.

**Comment by solardiz** [comment]
> @solardiz, where should @altjx get help with johnny?

Since @altjx isn't reporting a literal issue with any of our tools, not even with `johnny`, but merely needs advice on usage of the tools on EC2, this should ideally be discussed on the john-users mailing list: https://www.openwall.com/john/#lists https://www.openwall.com/lists/john-users/

Issues with Johnny can also be brought up in: https://github.com/openwall/johnny - but that's suboptimal in this case, because there's in fact no issue with Johnny per se here. (No other X app would run without a proper X tunneling setup and an X server, there's nothing specific to Johnny here.)

@altjx Are you comfortable joining john-users and continuing in there? Please let us know.

**Comment by solardiz** [comment]
I've just created the `question` label (with the same colors that GitHub's default `question` label uses, but with a different description) and assigned it here. While we could have reasonably used the `invalid` label for user support questions before - because those are not valid issues for the purposes of our issue tracking - I feel that could offend some people. So let's use this separate label in such cases.

@altjx Still waiting for you to tell us whether/where you'd like to continue discussing this.

**Comment by altjx** [comment]
Thanks @solardiz and @claudioandre-br  for your responses. For whatever reason I haven't received notifications on the replies here except for when the issue was closed. Sorry for the delay in responses and thanks for the quick replies!

All of the advice here is very helpful so I'll be joining the list and reaching out there for assistance. 

Thanks everyone!
