### ISSUE TITLE
zip2john does not return any hash value, gets "killed"

### ISSUE THREAD

**Issue by HugoGrinch** [openwall/john#4862]
hello so i tried practicing cracking zip file passwords using john the ripper in kali linux and the zip2john command does not return any hash value for the zip file i am cracking and it only returned this statement:

ver 2.0 Test.zip/123.zip PKZIP Encr: cmplen=2810975925, decmplen=2810975913, crc=388ABCA5 zsh: killed zip2john Test.zip

**Comment by magnumripper** [comment]
You have too little real or virtual memory for processing it (the file is huge).

**Comment by HugoGrinch** [comment]
> You have too little real or virtual memory for processing it (the file is huge).

i only use a virtual machine and i only alloted 2GB of ram, is it the main problem?

**Comment by magnumripper** [comment]
Sure. Try doubling it (provided the host has enough memory) and/or add a swapfile to Kali.

**Comment by HugoGrinch** [comment]
> Sure. Try doubling it (provided the host has enough memory) and/or add a swapfile to Kali.

hello sorry for the late reply, i tried doubling the ram by 4GB and it still gives me the same termination

**Comment by magnumripper** [comment]
So double it again or add a 4 GB swap file as well. The `zsh: killed zip2john Test.zip` is a tell tale that you ran out of memory. Right after it happens, you can try `dmesg | tail -20` and you'll probably see some log mentioning the "OOM_killer" killing your process to save the rest of the system.

**Comment by ghost** [comment]
You can (in fact, you should) run the zip2john tool using your host machine. 
* You don't need kali to use John the Ripper;
* You don't need a VM;
* You don't need LInux;
* There is also a GUI (but I guess you need to be a lucky guy to install it easily);

John the Ripper is a CLI tool, but it's pretty simple to use it for simple tasks. Nobody needs to be an expert to make it work. 

Just think about it the same way you would think about another tool with minimal hardware requirements. Or package dependencies. Or driver dependencies.

**Comment by solardiz** [comment]
Looking at `zip2john` source code and confirming with `ltrace`, it only needs roughly `cmp_len` bytes of memory, so just under 3 GB in this case. That 4 GB turned out to be insufficient suggests a lot of memory was also consumed elsewhere - e.g., was the output of `zip2john` perhaps _not_ redirected to a file, so the terminal emulator was trying to buffer it? That output would be almost 6 GB, thus needing 9 GB memory total. Alternatively, was the output possibly redirected to a file on tmpfs, thus needing memory rather than disk?

@HugoGrinch Please make sure you do redirect the output to a disk file, with at least 6  GB free. Then, to actually process that file `john` will need at least 6 GB memory anyway, so you will need to have at least this much in the VM as well.

**Comment by solardiz** [comment]
Not an issue we need to track, so I'll close this. Discussion can continue in here anyway.
