### ISSUE TITLE
Documentation is shit

### ISSUE THREAD

**Issue by s3rgeym** [openwall/john#4920]
Please add examples

**Comment by s3rgeym** [comment]
```bash
~/work/hack via 🐪 v5.34.0 via 🐘 via 🐍 v3.10.0 
➜ printf '1234567890' | md5sum
e807f1fcf82d132f9bb018ca6738a19f  -

~/work/hack via 🐪 v5.34.0 via 🐘 via 🐍 v3.10.0 
➜ john --wordlist=~/work/misc/10-million-password-list-top-1000000.txt --format=Raw-MD5 --rules <(echo e807f1fcf82d132f9bb018ca6738a19f)
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-MD5 [MD5 128/128 AVX 4x3])
Warning: no OpenMP support for this hash type, consider --fork=12
Press 'q' or Ctrl-C to abort, almost any other key for status
1234567890       (?)
1g 0:00:00:00 DONE (2021-12-08 04:22) 12.50g/s 2400p/s 2400c/s 2400C/s 123456..miller
Use the "--show --format=Raw-MD5" options to display all of the cracked passwords reliably
Session completed

~/work/hack via 🐪 v5.34.0 via 🐘 via 🐍 v3.10.0 
➜ john --wordlist=~/work/misc/10-million-password-list-top-1000000.txt --format=Raw-MD5 --rules <(echo e807f1fcf82d132f9bb018ca6738a19f)
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-MD5 [MD5 128/128 AVX 4x3])
No password hashes left to crack (see FAQ)

# > Use the "--show --format=Raw-MD5" options to display all of the cracked passwords reliably
# ok
# wtf???????????????????????????
~/work/hack via 🐪 v5.34.0 via 🐘 via 🐍 v3.10.0 
➜ john --wordlist=~/work/misc/10-million-password-list-top-1000000.txt --show --format=Raw-MD5 <(echo e807f1fcf82d132f9bb018ca6738a19f) 
Invalid options combination or duplicate option: "--show"

# pizdetz
~/work/hack via 🐪 v5.34.0 via 🐘 via 🐍 v3.10.0 
➜ john --show --format=Raw-MD5 <(echo e807f1fcf82d132f9bb018ca6738a19f) 
?:1234567890

1 password hash cracked, 0 left
```

Why does this shit only run once?

This utility is incredibly unintuitive. Hate: 9/10.

**Comment by AlekseyCherepanov** [comment]
Oh, I see the bit you miss: the cracked hashes are stored in `run/john.pot`, so you don't need to specify a wordlist to show cracked hashes, it is done almost instantly. But you may need to specify `--format=...` because same hash value can have different passwords depending on type (like md5(md5($p)) vs md5($p)). `--show` is not an option to just change output. `--show` is an "action". `--show` is used to query the "db", `--wordlist` is for attacks, hence `Invalid options combination`. Does it make sense now?

Also john skips hashes that are already cracked (it is important for speed with salted hashes). That's why it cracks your hash once only. john even said: `No password hashes left to crack (see FAQ)`. If you need to recrack hashes, you may specify other (empty) .pot file with `--pot=`.

What part of this explanation should be added to docs? And where? Into `doc/EXAMPLES`?

Hash cracking requires speed, so tools sacrifice convenience of usage to allow higher speeds and respective workflows. For instance, you cannot attack 2 hashtypes in one invocation with most tools: you have to start 2 attacks manually. Some things are very cumbersome and cannot be improved. In general, learning can be frustrating. It is twice frustrating with hash cracking because speed requires complexity. So I would welcome a suggestion of improvement to documentation that would work for you!

There is john-users mailing list for questions not going to grow into practical suggestions.

`<(echo e807f1fcf82d132f9bb018ca6738a19f)` is a nice trick!
