### ISSUE TITLE
Stribog format issues (Streebog, GOST R 34.11-2012)

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4974]
@vt-alt pointed out to me that the SSE4.1 implementation of Streebog that we use is actually slower than SSE2 and even than scalar reference. We could want to replace it, which would also enable these formats to work on systems without SSE4.1.

This prompted me to take a look, and other issues I notice are:

Why do we even call these two formats `Stribog*` when the actual English name for the hashes is Streebog? Should we rename?

Also, we define a `FORMAT_LABEL` in `stribog_fmt_plug.c`, but it's never used and the actual two format labels are different. We should probably at least drop the `FORMAT_LABEL` line, or replace it with two for labels that we actually use and then use those two new macros.

The "problem" is no one really cares about these formats after they've been used in a contest once (which is when and why they were added).

**Comment by magnumripper** [comment]
> The "problem" is no one really cares about these formats after they've been used in a contest once (which is when and why they were added).

We have quite a few of such formats, I guess. I kinda like supporting everything - I recall implementing a SHA format (the original SHA before SHA-1) just because I found it in OpenSSL. I thought it'd be cool to support it just in case someone find some very old data that would need it, but then they dropped that support and it's gone now. It'd probably be easy to find some reference code (wouldn't have to be optimized or SIMD) but it'll probably never be used anyway so why bother.

Perhaps we should create a `graveyard` directory and just move formats like these to it? Kinda like `unused` but for this specific use. For that SHA format it'd be mostly pointless as it depended on old OpenSSL but for Streebog it could be a good place for resting in peace.

**Comment by solardiz** [comment]
Unlike the original SHA, Streebog is still a current algorithm that people use. There's now gost-yescrypt, which uses it on the outer layer - we'll probably need to add that eventually, at which time we'll need Streebog in tree again. So we could as well keep the raw versions. In fact, @vt-alt also suggested we need micro-benchmarks of the primitives that we use - well, having raw hash formats provides that. So I think we should keep.

**Comment by ghost** [comment]
> We have quite a few of such formats

That was the first thing I thought when I read the Solar post.

> Perhaps we should create a `graveyard` directory and just move formats like these to it?

I like the idea.

Maybe we can also have something like `experimental` to put new formats (accept new contributions more easily and faster, maybe).

**Comment by vt-alt** [comment]
> gost-yescrypt

(Which is supported in [libxcrypt](https://github.com/besser82/libxcrypt)). AFAIK, of current and real uses there is also _Astra Linux_-only Streebog-based `crypt()`, but I'm not sure it have interest to be supported.

**Comment by vt-alt** [comment]
> The "problem" is no one really cares about these formats after they've been used in a contest once (which is when and why they were added).

Btw, does it mean it was never practical, but contest invented usage?

ps.
> Why do we even call these two formats `Stribog*` when the actual English name for the hashes is Streebog?

Perhaps, because of php-stribog (created in 2013).
```
src/stribog_fmt_plug.c:5: * Based on https://www.streebog.net/ and https://github.com/sjinks/php-stribog
```
In 2013 it was still unclear of official English transliteration of _Стрибог_, so in 2013-2014 there was still many scientific papers saying _Stribog_. Also, it was obvious reference to Stribog god which is traditionally named as Stribog and never Streebog. (Perhaps, they wanted the official transliteration to be distinguishing for it).
But ofc now official name is well known.

**Comment by solardiz** [comment]
> does it mean it was never practical, but contest invented usage?

Yes, I'm not aware of any real uses of raw Streebog for password hashing. This doesn't mean that none exist anywhere, though.

**Comment by vt-alt** [comment]
> > does it mean it was never practical, but contest invented usage?
> 
> Yes, 

IC. This means improving Streebog impl. without adding real password hash support will be meaningless.
