### ISSUE TITLE
Extract hashes to .json file Blockchain wallet v4

### ISSUE THREAD

**Issue by FABIOTOP** [openwall/john#4986]
hi
I need to extract hash from .json blockchain wallet version 4 v4 file.
how to extract hash from blockchain wallet version 4 where it locates the access password to recover account

**Comment by solardiz** [comment]
Hi @FABIOTOP. This is an issue tracker, not a support forum. Your edited comment says that an update is needed (you also say "urgent", but we don't view it that way) - if so, maybe we can re-label your issue from "question" to requested "enhancement" (and likely let it stay open for a long while, as it doesn't appear anyone would work on this soon given that other open issues related to Blockchain wallet support didn't get much attention).

One thing you could do to help make progress at this issue is provide a sample `.json` file for a version 4 wallet, with a known password that you'd also provide and no funds on the wallet. Thanks.

**Comment by solardiz** [comment]
The same issue is now reported in #5078, but with more detail. So I'll close this one in favor of the newer one.
