### ISSUE TITLE
Can someone crack this file for me? I have no clue what i'm doing

### ISSUE THREAD

**Issue by MoorDoor** [openwall/john#5124]
I have no clue how to do any of this, i'm just trying to open this dmg file that contains an mp3/wav file. Can someone help me?

**Comment by solardiz** [comment]
@MoorDoor We don't normally use GitHub issues to provide user support (we use them to track problems in our software), and besides you're not even asking for support - you're asking for someone to do the job for you. If you need this for legitimate business, please feel free to request this as a paid service from Openwall (not cheap, and success is far from certain). Otherwise you're most likely out of luck. Either way, it's not a valid GitHub issue for us to track, so closing.
