### ISSUE TITLE
Homebrew missing unshadow

### ISSUE THREAD

**Issue by sv7ter** [openwall/john#5136]
I have succesfully installed John-jumbo(Mac os Monterey, M1), via Brew. I am able to use it, BUT unshadow is not included. I am using unshadow from the CMD line in a terminal box, with the correct required arguments/options. But it is not recognized as a command (whlie john is). Like: zsh: command not found: unshadow. What is wrong? 

Build info:

Version: 1.9.0-jumbo-1
Build: darwin21.1.0 64-bit arm ASIMD AC
SIMD: ASIMD, interleaving: MD4:2 MD5:2 SHA1:1 SHA256:1 SHA512:1
System-wide exec: /opt/homebrew/Cellar/john-jumbo/1.9.0/share/john
System-wide home: /opt/homebrew/Cellar/john-jumbo/1.9.0/share/john
Private home: ~/.john
$JOHN is /opt/homebrew/Cellar/john-jumbo/1.9.0/share/john/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
clang version: 13.0.0 (clang-1300.0.29.3) (gcc 4.2.1 compatibility)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 0101010cf	(loaded: 0101010ff)
OpenSSL 1.1.1l  24 Aug 2021	(loaded: OpenSSL 1.1.1o  3 May 2022)
GMP library version: 6.2.1
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by solardiz** [comment]
@sv7ter This looks like a maybe-issue with the Brew package, which we - contributors to this repository - are not involved in maintaining, and are not familiar with. So we wouldn't be able to help, and you might want to report the issue to maintainers of the package instead.

One thing you could want to check, though, is whether `unshadow` is installed but is just not in search `PATH` (in which case you might be able to invoke it via its full path), or whether it's not installed at all.

Also, why do you even need `unshadow` on a Mac? My guess is you possibly don't, unless you have separately copied `passwd` and `shadow` files from another Unix system maybe?

Edit: In general, though, a Mac package _should_ in fact provide `unshadow`, because _some_ users will need it, so not providing it _is_ a package bug.

I'll close the issue since it's not an issue with anything in this repository, and thus not anything we need to keep track of. However, please feel free to add more comments to the closed issue.

**Comment by sv7ter** [comment]
Thanks for answering solardiz.
You are right, i do not need it for my Mac, but i need it for doing (security/pentest) exercises. Everything is working with john, only the unshadow part. I will check with Brew. If i do a john, this is displayed, so that's why i started here. 

John the Ripper 1.9.0-jumbo-1 [darwin21.1.0 64-bit arm ASIMD AC]
Copyright (c) 1996-2019 by Solar Designer and others
Homepage: http://www.openwall.com/john/

Yes probably a Homebrew package bug...i will have to look where to report that.

**Comment by solardiz** [comment]
Anyway, I just took a look at:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/john-jumbo.rb

which has this:

```
    # Only symlink the main binary into bin
    (share/"john").install Dir["run/*"]
    bin.install_symlink share/"john/john"
```

So it's a deliberate decision by the package maintainer(s) not to provide tools other than `john` in default search path. Looks like you'd need to run them via full paths, so e.g.:

```
/opt/homebrew/Cellar/john-jumbo/1.9.0/share/john/unshadow
```

That's fine, but maybe could be documented by the package somewhere - e.g., you could suggest them to have this printed in usage instructions upon package installation. (Not only about `unshadow`, but also and mostly about the many other additional tools we provide in there.)

FWIW, it was different in non-jumbo package, where they did install the `un*` tools:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/john.rb

```
    %w[john unafs unique unshadow].each do |b|
      bin.install "run/#{b}"
    end
    pkgshare.install Dir["run/*"]
```

That difference makes sense to me because jumbo provides way too many tools to have all of them installed in or symlinked from `bin`.

**Comment by sv7ter** [comment]
Wow, thanks alot , that solved it...!!!!
