### ISSUE TITLE
Opencl and Fedora 36

### ISSUE THREAD

**Issue by e2002e** [openwall/john#5161]
I'm not sure whether it's a bug. Probably only a missing path due to new cuda versions, but opencl is not recognized.
I did follow [this procedure](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Fedora&target_version=35&target_type=rpm_locall) and can confirm that other softwares using opencl are working.
./configure finds the headers but not the library.
I did try to add libraries paths to ld.so.conf.d/ and ran ldconfig. Nothing will do.
My system is fedora 36 workstation.
I'm quite sure it did work with other linuxes, at least Ubuntu and Parrot.
Any help appreciated.

**Comment by solardiz** [comment]
@e2002e Our example in `README-OPENCL` gives:

```
./configure LDFLAGS=-L/usr/local/cuda-11.0/targets/x86_64-linux/lib CPPFLAGS=-I/usr/local/cuda-11.0/targets/x86_64-linux/include
```

Since you say the headers are found on their own, you shouldn't need the `CPPFLAGS` part, but since the library is not found you apparently _do_ need the `LDFLAGS` part.

Alternatively, instead of a command like the above, you can do something like the below (as root):

```
cd /usr/local
ln -s cuda-11.0 cuda
```

and then simple `./configure` would just work - until you upgrade CUDA and need to update the symlink accordingly.

Of course, you'll need to substitute your actual CUDA version number in there.

Please let us know of your results, and of the exact commands you end up using.

By the way, while we describe OpenCL setup in our `INSTALL-UBUNTU`, we currently don't in our `INSTALL-FEDORA` - we might want to add some distro-specific instructions to the latter as well, unless there's a reason not to.

**Comment by e2002e** [comment]
I switched to Debian, there it went smoothly.
I am quite sure that Fedora was using cuda 11.4 and that there was a libcuda.so in /usr/lib/x86_64 just like in Debian.
I have a lot of performance improvement with this system, about (two hundred millions on two billions) / secs for md5.

**Comment by e2002e** [comment]
I am again on Fedora and ran the first piece of code you gave me, simply replacing 11.0 with 11.7 and it works :)
