### ISSUE TITLE
bitlocker2john is unnecessarily slow to output a "hash"

### ISSUE THREAD

**Issue by Popzindawood** [openwall/john#5163]
Hello,

I would like to know how long does it takes for bitlocker2john to extract hashs from a m2 (500go) ? 

Thanks ! :)

**Comment by Popzindawood** [comment]
it displays :

"VMK entry found at 0x1e6ad61380" since morning... 
Maybe bug..? or am I too impatient xD

**Comment by magnumripper** [comment]
Yeah that sounds like a bug to me, although I'm not really acquainted with that tool. Even if it had to scan all 500 MB it shouldn't take that long.

**Comment by solardiz** [comment]
@e-ago @kholia @visuve Maybe you can comment on this issue? Thanks!

@Popzindawood Has the job completed? How long did it take? Did it produce output that `john` accepts for cracking?

The function `process_encrypted_image()` does appear to read the full file, and in a rather inefficient way, unconditionally. It is possible that @visuve's recent fix exacerbated the problem: maybe the program just happened not to read beyond 2 or 4 GiB before that fix, and maybe that was usually enough.

I think we need to add at least this:

```diff
+++ b/src/bitlocker2john.c
@@ -237,6 +237,8 @@ int process_encrypted_image(char *image_path)
                                fprintf(stdout, "\n\n");
                                fflush(stdout);
                                recoveryPasswordFound = 1;
+                               if (userPasswordFound)
+                                       break;
                        }
                        else if ((c == key_protection_password[0]) && (d == key_protection_password[1]) && userPasswordFound == 0) {
                                fprintf(stderr, "\nVMK encrypted with User Password found at %llx\n", (long long)fp_before_salt);
@@ -270,6 +272,8 @@ int process_encrypted_image(char *image_path)
                                fprintf(stdout, "\n\n");
                                fflush(stdout);
                                userPasswordFound = 1;
+                               if (recoveryPasswordFound)
+                                       break;
                        }
                }
 
```

So that when _both_ kinds of entries have already been found, the loop terminates early. However, maybe that's not enough - maybe we also need to let it terminate when it finds one of these entries? Or maybe we need to output the "hash" (and `fflush` the output stream) as soon as we have it, not when the loop terminates, so that the user can interrupt early (without waiting for the other kind of entry to possibly also be found).

**Comment by solardiz** [comment]
FWIW, according to https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-key-management-faq#where-are-the-encryption-keys-stored "The keys are also saved to two additional locations on the drive for redundancy." So perhaps letting `bitlocker2john` continue the search is expected to result in it finding those two additional copies, and perhaps there are inconsistent disks/images where the additional copies could differ... including being for a different (older or newer) password? Anyway, not outputting anything until the entire device or image is processed feels wrong.

**Comment by solardiz** [comment]
@Popzindawood Any update from you? Also, `bitlocker2john` from what version/build of JtR on what OS did you use?
