### ISSUE TITLE
Alternative to _mm_loadu_si128

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#5172]
Found when investigating https://github.com/gost-engine/engine/blob/master/gosthash2012_sse2.h (#5169)

```c
#ifdef __SSE3__
/*
 * "This intrinsic may perform better than _mm_loadu_si128 when
 * the data crosses a cache line boundary."
 */
# define UMEM_READ_I128 _mm_lddqu_si128
#else /* SSE2 */
# define UMEM_READ_I128 _mm_loadu_si128
#endif
```
@solardiz would you think we should try this for our `vloadu` pseudo-intrinsic? I'm not sure how to test it though, I think we normally stay within cache lines. Perhaps better just have a look at data from Agner Fog.

**Comment by solardiz** [comment]
We'd need to find a P4 or a "Core1" Intel CPU to test. I think we don't care enough.

This is a good explanation:

https://stackoverflow.com/questions/38370622/a-faster-integer-sse-unalligned-load-thats-rarely-used#38383624

Essentially, by using this instruction we tell the CPU that we know the underlying memory is OK for such use (not some kind of uncached/MMIO space).

We could just use `lddqu` on SSE3+ without testing for performance effects, however this mentions a case where we should not:

https://www.felixcloutier.com/x86/lddqu

"In situations that require the data loaded by (V)LDDQU be modified and stored to the same location, use (V)MOVDQU or (V)MOVDQA instead of (V)LDDQU."

So we'd either need to examine our data flow or actually test on a P4.

**Comment by magnumripper** [comment]
Case closed then, thanks!
