### ISSUE TITLE
Build error of a third-party package on a mobile device - .a files not found

### ISSUE THREAD

**Issue by Darkrevengehack** [openwall/john#5209]
El problema es durante y al final de la instalación:

![Screenshot_20221027-173133](https://user-images.githubusercontent.com/103399387/198393289-152fd501-c3ff-452f-aefa-2f5ea9b731f5.png)

**Comment by solardiz** [comment]
Looks like a dupe of #5109, which we never figured out - it's people reporting issues with some unmentioned third-party package, maybe part of a packages repository used by `termux` on Android or similar. Such reports are thus misdirected (should be to the packager, not us), but we can talk in here anyway - if needed, even after we close the issue (which I think we'll do soon because this isn't our issue that we need to track).

My best guess is whatever package this is, is missing a required build-time dependency. However, like I mentioned in the other issue, the obvious culprit - whichever package provides `ar` - might not be it, as removing `ar` from a (very different) system didn't trigger the same failure mode for me.

**Comment by Darkrevengehack** [comment]
> Parece un engaño de #5109 , que nunca descubrimos: son personas que informan problemas con un paquete de terceros no mencionado, tal vez parte de un repositorio de paquetes utilizado `termux`en Android o similar. Por lo tanto, dichos informes están mal dirigidos (deberían ser para el empaquetador, no para nosotros), pero podemos hablar aquí de todos modos, si es necesario, incluso después de cerrar el problema (lo que creo que haremos pronto porque este no es nuestro problema que necesitamos rastrear).
> 
> Mi mejor suposición es que, sea cual sea el paquete, falta una dependencia de tiempo de compilación requerida. Sin embargo, como mencioné en el otro problema, el culpable obvio, cualquiera que sea el paquete que proporcione `ar`, podría no serlo, ya que la eliminación `ar`de un sistema (muy diferente) no provocó el mismo modo de falla para mí.

bro, thanks for the contribution, you have a very well programmed tool to detect the operating system and make it work based on the linux operating system, congratulations!!!
