### ISSUE TITLE
How is John upgraded on Android termux?

### ISSUE THREAD

**Issue by Darkrevengehack** [openwall/john#5213]
Hello, I would like to know how John the ripper is updated

**Comment by solardiz** [comment]
@Darkrevengehack You'll need to make your question more specific - how is John updated by who (e.g., by an end-user, by a distro, by us developers/maintainers), how it was obtained/built/installed/packaged/whatever initially ("updating" implies one already has it in some form), and on what system. Otherwise the issue you opened is basically a hint for us to write more documentation, but that can take ages given we somehow didn't write such generic part of documentation on updating so far.

Also, historically we were using the `john-users` mailing list for end-user questions (if yours is that), and they're still de-prioritized here on GitHub issues (which we primarily use literally for issue tracking, not for questions/answers). Given that this isn't an issue we need to track, I'll plan on closing it, but please feel free to add more comments to it anyway (even after it's closed).

**Comment by Darkrevengehack** [comment]
> @DarkrevengehackDeberá hacer su pregunta más específica: cómo se actualiza John por quién (por ejemplo, por un usuario final, por una distribución, por nosotros los desarrolladores/mantenedores), cómo se obtuvo/creó/instaló/empaquetado/lo que sea inicialmente ("actualizar" implica que uno ya lo tiene de alguna forma), y en qué sistema. De lo contrario, el problema que abrió es básicamente una sugerencia para que escribamos más documentación, pero eso puede llevar años dado que de alguna manera no escribimos una parte tan genérica de la documentación sobre la actualización hasta ahora.
> 
> Además, históricamente estábamos usando la `john-users`lista de correo para las preguntas de los usuarios finales (si la suya es esa), y todavía no tienen prioridad aquí en los problemas de GitHub (que usamos principalmente literalmente para el seguimiento de problemas, no para preguntas/respuestas). Dado que este no es un problema que debamos rastrear, planearé cerrarlo, pero no dude en agregar más comentarios de todos modos (incluso después de que esté cerrado).

I want to update john the ripper in termux app for Android, root is not needed to use the app, it is in armv7l in termux version 0.118 (Official Stable Version)

**Comment by solardiz** [comment]
I've never used John the Ripper on termux, but I just did some searching.

I suppose there are two ways to upgrade:
1. Remove the previous installation (which could be simply `rm -rf john`) and repeat the installation instructions you had used (if those install the latest revision, e.g. like these appear to - https://github.com/azclub-ltd/Termux-JohnTheRipper-Installer). You might want to save the `john.pot` file (move outside of `john`) and restore it (move it back inside), so that you retain the cracked passwords.
2. If the installation instructions were such that they used our git repo (like those I found appear to do), you can use the command `git pull` to update the source code to the latest, then repeat `./configure && make -sj4` or such inside that directory (if we only made minor updates since you installed, you could skip the `./configure` step and only do `make -sj4`, which is quicker but is not always reliable). That way, you don't need to save/restore `john.pot` (it just stays where it is) and the build could be quicker (not necessarily a full rebuild).

FWIW, besides the instructions above, I also found two videos, both of which also use our git repo. One installs directly on termux, the other inside an added Linux distro in termux:
https://www.youtube.com/watch?v=TfoNoMCzOVE
https://www.youtube.com/watch?v=jEzUT34nABw

Having only found these, I guess there isn't a package of John the Ripper for termux? If so, you don't upgrade it as a package.

**Comment by snooppr** [comment]
JtR is installed from source, according to the documentation install ubuntu on termux.  To update, use "cd john && git stash && git pull" and recompile.

![john_Termux 2023](https://user-images.githubusercontent.com/61022210/224617687-585a1219-728b-447f-ac1e-5af217d93db8.png)
