### ISSUE TITLE
./pseudo_intrinsics.h:110:25: error: use of 'long long' with '__vector' requires VSX support (available on POWER7 or later) to be enabled

### ISSUE THREAD

**Issue by pkubaj** [openwall/john#5231]
Build on ppc64 (big-endian) fails without adding -mvsx to CFLAGS:
```
cc -DAC_BUILT -DJOHN_ALTIVEC -c -m64 -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -I/usr/local/include -I/usr/include -DARCH_LITTLE_ENDIAN=0 -DJOHN_SYSTEMWIDE -DJOHN_SYSTEMWIDE_EXEC='"/usr/local/bin"' -DJOHN_SYSTEMWIDE_HOME='"/usr/local/share/john"'  -DJOHN_SYSTEMWIDE=1 -Wall -Wno-tautological-constant-out-of-range-compare -fno-omit-frame-pointer -Wno-deprecated-declarations -Wformat-extra-args -Wunused-but-set-variable -Qunused-arguments -std=gnu89 -Wdate-time -D__BSD_VISIBLE -I/usr/include -fopenmp  -D_THREAD_SAFE -pthread -I/usr/local/include -DCL_SILENCE_DEPRECATION -funroll-loops -O1 john.c
In file included from john.c:109:
In file included from ./dynamic.h:30:
In file included from ./simd-intrinsics.h:19:
./pseudo_intrinsics.h:110:25: error: use of 'long long' with '__vector' requires VSX support (available on POWER7 or later) to be enabled
typedef vector unsigned long long vtype64;
                        ^
1 error generated.
```

This is FreeBSD 14.0-CURRENT with LLVM 14.0.5.

**Comment by solardiz** [comment]
Thank you for reporting this. Did you also run into #5203, and if not any idea why not?

**Comment by solardiz** [comment]
@pkubaj Do you possibly want to develop, test, and contribute a fix for this issue and/or for #5203? We'd appreciate that.

**Comment by pkubaj** [comment]
It would be difficult to do without a rewrite. vector long is deprecated and should not be used. vector long long requires VSX, so fixing it would require avoiding any vector longs (or long longs).

**Comment by solardiz** [comment]
No, I think you're looking at it wrongly.

I notice you reported this error for building `john.c` rather than some other source file. That one is special in that we deliberately avoid enabling SIMD for it, so that it wouldn't crash on an older CPU incapable of those instructions, but would rather be able to exec a fallback binary that is entirely built without SIMD (or with dependency on fewer SIMD extensions).

If it were not for that deliberate and well-reasoned lack of SIMD options in there, we could simply have our `configure` script add `-mvsx` or whatever other SIMD options it's using when building other source files in the tree. However, here a proper fix may be to avoid including `simd-intrinsics.h` when building `john.c`. If we do need something from `dynamic.h` in there, then maybe we should split `dynamic.h` in two or introduce conditional compilation in there.

**Comment by pkubaj** [comment]
The following patch seems to work fine:
```
@@ -106,7 +106,6 @@
 #include "subsets.h"
 #include "external.h"
 #include "batch.h"
-#include "dynamic.h"
 #include "dynamic_compiler.h"
 #include "fake_salts.h"
 #include "listconf.h"
@@ -137,6 +136,8 @@
 #endif
 #endif
 #include "omp_autotune.h"
+
+extern int dynamic_Register_formats(struct fmt_main **ptr);
 
 #if CPU_DETECT
 extern int CPU_detect(void);
```

**Comment by solardiz** [comment]
@pkubaj Cool. Please submit a PR with this patch. Thanks!
