### ISSUE TITLE
ZIP cracking does not detect any password hashes

### ISSUE THREAD

**Issue by UniqueUsernam** [openwall/john#5256]
ZIP password cracking via `zip2john` and then `john` does not detect any password hashes on macOS Ventura 13.2.1.

### STEPS TO REPRODUCE ###
1. Create an encrypted ZIP file on macOS Ventura 13.2.1, the latest version of macOS as of writing this, out of a folder or one or more files. Set the password to anything you want.
`zip -P monkeysEatBananas hacker.txt hacker.zip`
2. Get the password hash from the ZIP file with `zip2john`, and save it in a file.
`zip2john hacker.zip > ziphashes.txt`
3. Attempt to crack the password with `john`.
`john ziphashes.txt`
The result:
`Using default input encoding: UTF-8`
`No password hashes loaded (see FAQ)`
### EXAMPLE ###
1. `echo 'I am a file in an encrypted ZIP archive.' > hacker.txt
Output: none
2. `zip -P monkeysEatBananas hacker.zip hacker.txt'`
Output:
`  adding: hacker.txt (deflated 10%)`
3. `zip2john hacker.zip > ziphashes.txt`
Output:
`ver 2.0 efh 5455 efh 7875 hacker.zip/hacker.txt PKZIP Encr: 2b chk, TS_chk, cmplen=58, decmplen=51, crc=B4BE2804`
ziphashes.txt file contents:
`hacker.zip/hacker.txt:$pkzip2$1*2*2*0*3a*33*b4be2804*0*44*8*3a*b4be*4289*b813f1236a3cf5c4b0dafb2a26acf23ee96694fece949824b482e6a10c968540aa16296ade568daab3aa18c6e09769cb89208eb60d26336b4e13*$/pkzip2$:hacker.txt:hacker.zip::hacker.zip`
4. `john ziphashes.txt`
Output:
`Using default input encoding: UTF-8`
`No password hashes loaded (see FAQ)`

I have tried using `john --format=zip`, which yields the same result.
**The exact same set of steps detailed in the example works when `john` is run on the latest version of Kali Linux.**
[hacker.zip](https://github.com/openwall/john/files/10982140/hacker.zip)
[ziphashes.txt](https://github.com/openwall/john/files/10982165/ziphashes.txt)
### john --list=build-info ###
> Version: 1.9.0-jumbo-1
> Build: darwin22.3.0 64-bit x86_64 SSE4.2 AC
> SIMD: SSE4.1, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
> System-wide exec: /usr/local/homebrew/Cellar/john-jumbo/1.9.0_1/share/john
> System-wide home: /usr/local/homebrew/Cellar/john-jumbo/1.9.0_1/share/john
> Private home: ~/.john
> CPU tests: SSE4.2
> $JOHN is /usr/local/homebrew/Cellar/john-jumbo/1.9.0_1/share/john/
> Format interface version: 14
> Max. number of reported tunable costs: 4
> Rec file version: REC4
> Charset file version: CHR3
> CHARSET_MIN: 1 (0x01)
> CHARSET_MAX: 255 (0xff)
> CHARSET_LENGTH: 24
> SALT_HASH_SIZE: 1048576
> SINGLE_IDX_MAX: 2147483648
> SINGLE_BUF_MAX: 4294967295
> Effective limit: Number of salts vs. SingleMaxBufferSize
> Max. Markov mode level: 400
> Max. Markov mode password length: 30
> clang version: 14.0.0 (clang-1400.0.29.202) (gcc 4.2.1 compatibility)
> OpenCL headers version: 1.2
> Crypto library: OpenSSL
> OpenSSL library version: 030100000
> OpenSSL 3.1.0 14 Mar 2023
> GMP library version: 6.2.1
> File locking: fcntl()
> fseek(): fseek
> ftell(): ftell
> fopen(): fopen
> memmem(): System's

### COMMAND LINE INFO ###
I am using the `bash` shell with macOS's built-in `Terminal` application.
Output from `bash --version`:
> GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
> Copyright (C) 2007 Free Software Foundation, Inc.

🥇 👍 😕

**Comment by magnumripper** [comment]
You need to use the latest version from here, not latest "release".

**Comment by UniqueUsernam** [comment]
I installed John the Ripper with `brew install john-jumbo`, shouldn't that give me the latest version?

**Comment by UniqueUsernam** [comment]
@magnumripper I installed John the Ripper Jumbo with `brew install john-jumbo`, shouldn't that give me the latest version?

**Comment by ghost** [comment]
`john` from this repository works fine.
```
$ john-the-ripper.zip2john hacker.zip > hash.txt
ver 2.0 efh 5455 efh 7875 hacker.zip/hacker.txt PKZIP Encr: TS_chk, cmplen=58, decmplen=51, crc=B4BE2804 ts=4289 cs=4289 type=8

$ john hash.txt -mask=monkeysEatBanan?l?l
Using default input encoding: UTF-8
Loaded 1 password hash (PKZIP [32/64])
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
monkeysEatBananas (hacker.zip/hacker.txt)     
1g 0:00:00:00  1.612g/s 1090p/s 1090c/s 1090C/s monkeysEatBananaa..monkeysEatBananqq
Use the "--show" option to display all of the cracked passwords reliably
Session completed. 
```

> brew install john-jumbo, shouldn't that give me the latest version?

I'm afraid you are asking this question in the wrong place: only brew maintainers know what they are packaging. 

Either way, you're getting the latest release (as in released software), not the latest version (commit available in GitHub).
*****

Well, since there is no issue we should care, we'll close this soon.

**Comment by magnumripper** [comment]
> @magnumripper I installed John the Ripper Jumbo with `brew install john-jumbo`, shouldn't that give me the latest version?

Perhaps it "should" but apparently it didn't. That's up to the package maintainer and not us.

**Comment by solardiz** [comment]
> Well, since there is no issue we should care, we'll close this soon.

I think we should care. I do care. This is our reminder, primarily for me, that we should make a new numbered release sooner rather than later, to signal packagers to pick up our new code.

What you meant is it's not an issue we should track. That's exactly right, and yes let's close it - but it has worked as that reminder I mentioned.

**Comment by solardiz** [comment]
FWIW, our latest `john` from here cracks this password even when given the old `zip2john` "hash" posted by @UniqueUsernam, even though the "hash" looks different from what our new `zip2john` produces. Given the kind of issues we fixed in our PKZIP support since last release, I think this behavior is not guaranteed (to get all fixes, need to use new versions of both tools), but we're lucky this time.

The info + "hash" posted above is:

```
ver 2.0 efh 5455 efh 7875 hacker.zip/hacker.txt PKZIP Encr: 2b chk, TS_chk, cmplen=58, decmplen=51, crc=B4BE2804
hacker.zip/hacker.txt:$pkzip2$1*2*2*0*3a*33*b4be2804*0*44*8*3a*b4be*4289*b813f1236a3cf5c4b0dafb2a26acf23ee96694fece949824b482e6a10c968540aa16296ade568daab3aa18c6e09769cb89208eb60d26336b4e13*$/pkzip2$:hacker.txt:hacker.zip::hacker.zip
```

The new one is:

```
ver 2.0 efh 5455 efh 7875 hacker.zip/hacker.txt PKZIP Encr: TS_chk, cmplen=58, decmplen=51, crc=B4BE2804 ts=4289 cs=4289 type=8
hacker.zip/hacker.txt:$pkzip$1*1*2*0*3a*33*b4be2804*0*44*8*3a*4289*b813f1236a3cf5c4b0dafb2a26acf23ee96694fece949824b482e6a10c968540aa16296ade568daab3aa18c6e09769cb89208eb60d26336b4e13*$/pkzip$:hacker.txt:hacker.zip::hacker.zip
```

There is not much difference in speed, even though IIRC we switch from 2-byte checksum to 1-byte for early rejects (to be compatible with more ZIP archivers)... or do we do that even for old "hashes" that say 2-byte - I don't recall.

Sharing this in here just in case we end up investigating related issues later.

Update: Just after I wrote the above, I tested with our 1.9.0-jumbo-1 release - and it, too, is able to crack this, both using the "hash" @UniqueUsernam posted and going from the ZIP file. So the issue may be somehow specific to the Brew build or its usage by @UniqueUsernam. This is puzzling and unexpected.

@UniqueUsernam Can you double-check how you used the tools? For example, one issue I've seen people run into on macOS is using a text editor on the file containing the "hash", which sometimes results in it becoming RTF instead of plain text. You do show you use output redirection, which should have worked just fine, but maybe you simplified for reporting the issue in here and you had actually used copy-paste via a text editor? Just guessing, and I'm probably wrong here.

This issue is closed since we don't need to track it, but it's OK to discuss in more comments.

**Comment by solardiz** [comment]
Also not much change in speed between 1.9.0-jumbo-1 and our latest code. I tested single-threaded and 32x OpenMP. In fact, the new code is slightly faster in my tests, but that could be random fluctuation.

**Comment by UniqueUsernam** [comment]
@solardiz I did not open the hash file with a text editor, and I used the exact steps posted here. I've had trouble installing John the Ripper Jumbo from this GitHub repository, so I decided to use `brew`, but it turns out maybe that wasn't the greatest idea. Given the fact that this works on Kali Linux, where John the Ripper Jumbo came with the distribution automatically, I'll keep at it trying to install from source.

**Comment by UniqueUsernam** [comment]
**Update:** I built the package from source (finally), my system had some configuration issues. `zip2john` works fine now, it finds the password. I hope `brew` eventually figures out it packaged the wrong code! Thanks for your support.
