### ISSUE TITLE
我想问一下，我的结果已经破解出来了，但是为什么输出的原hash值为“？”

### ISSUE THREAD

**Issue by jingxdy** [openwall/john#5276]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/93567493/231384149-dffbd262-1dab-4dc1-aa44-6c23ce683f22.png">
?:1553
?:sdgs
?:jngn
?:9009
?:123
目前我没有翻到其他人遇到这个情况，我使用的是John-jumbo，希望能帮我回答，谢谢

**Comment by magnumripper** [comment]
On-line translation (it would have been nice if you did this yourself before posting):
> I want to ask, my result has been cracked, but why is the original hash value of the output?
> At present, I haven't found anyone else in this situation. I'm using John-jumbo. I hope you can help me answer. Thank you.

I think you wanted to say "why can't I see the original hash in the crack output" as it gets hard to see which password goes where.

I assume your input file `md5hash.txt` looks like this:
```
<hash1>
<hash2>
(...)
```
You could instead format it like this:
```
<username1>:<hash1>
<username2>:<hash2>
(...)
```
Then, instead of `?:1553` you will get output such as `username:1553`.

If you don't have any usernames but want to see the actual hashes, you could format the input file like this:
```
<hash1>:<hash1>
<hash2>:<hash2>
(...)
```
So the "username" will be the original hash and output will look like `18ead4c77c3f40dabf9735432ac9d97a:1553`. I have pondered adding some option to do this without hacking the input file, see https://github.com/openwall/john/issues/5074#issuecomment-1085959149

**Comment by magnumripper** [comment]
For getting the `hash:hash` input format with `hash:password` output, you could run this:
```
perl -pe 's/(.*)/$1:$1/' md5hash.txt > newfile.txt
john --show newfile.txt
```

**Comment by jingxdy** [comment]
Thank you, I understand now.
