### ISSUE TITLE
Crash recovery file is locked: /root/.john/john.rec

### ISSUE THREAD

**Issue by santoshdawre** [openwall/john#5317]
──(root㉿kali)-[~/Desktop]
└─# john mykey.txt                                        
Warning: detected hash type "wpapsk", but the string is also recognized as "wpapsk-pmk"
Use the "--format=wpapsk-pmk" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1 password hash (wpapsk, WPA/WPA2/PMF/PMKID PSK [PBKDF2-SHA1 256/256 AVX2 8x])
Will run 10 OpenMP threads
Note: Minimum length forced to 8 by format
Proceeding with single, rules:Single
Crash recovery file is locked: /root/.john/john.rec
[mykey.txt](https://github.com/openwall/john/files/11718028/mykey.txt)

**Comment by solardiz** [comment]
@santoshdawre This error message means that you already have another instance of `john` running concurrently. You generally shouldn't run more than one instance at a time, although we do support that as let's say expert usage, where you'd need to manually specify different tasks and different session names for the different instances.

If you have specific questions, please feel free to ask. As it is, your message wasn't even worded as a question.

Edit: although I've just closed this issue since we don't need to track it (not really an issue), you can add more comments to it if you need to.

**Comment by mohammedv10** [comment]
Using default input encoding: UTF-8

 Loaded 1 password hash (Raw-MD4 [MD4 256/256 AVX2 8x3])

 Proceeding with single, rules:Single

 Crash recovery file is locked: /root/.john/john.rec استخدام ترميز الإدخال الافتراضي: UTF-8
وش الحل

**Comment by ghost** [comment]
As stated above it `means that you already have another instance of john running concurrently.` 

To "get around" this, `you'd need to manually specify [...] different session names for the different instances`.
