### ISSUE TITLE
john status shows threads before/after main status

### ISSUE THREAD

**Issue by blandyuk** [openwall/john#5342]
Just a small issue, nothing major, but noticed when getting a status update on john, the GPU threads are befpre/after the main status details. Example:

![image](https://github.com/openwall/john/assets/22078464/6821d58d-85be-4ec4-b739-ded0a6d7d693)

Had this with my threaded apps, so know of the issue.

Would be better if it displays the main status details first, then the individual GPU status/speeds, like as below. Also, worth adding a blank line before outputting to show separation between status updates, like in my example above also.

Worth adding a --status-update-timer=60 command to control john automatically showing status every 60 seconds, (user defined). If command not specified, don't do a status update.

Remaining hashes    1 (0 removed)
Remaining salts     1 (0 removed)
Time in seconds     873.87 (873.87 new)
Successful guesses  0 (0 new, 0 g/s)
Passwords tested    20471808 (20471808 new, 23426 p/s)
 dupe suppressor    is disabled
 and it accepted    0 (0.00%, 0 p/s)
        rejected    0 (0.00%, 0 p/s)
    out of total    0 (0 p/s)
Hash computations   20471808 (20471808 new, 23426 c/s)
Hash combinations   20471808 (20471808 new, 23426 C/s)
1 0g 0:00:14:33 26.43% (ETA: 10:44:38) 0g/s 23426p/s 23426c/s 23426C/s ea4314055..ruffybobby11
3 0g 0:00:14:34 25.72% (ETA: 10:46:14) 0g/s 22776p/s 22776c/s 22776C/s 64c1eeba..harrytate19
2 0g 0:00:14:34 26.25% (ETA: 10:45:05) 0g/s 23239p/s 23239c/s 23239C/s 1334561336..elasah1022

**Comment by solardiz** [comment]
> Would be better if it displays the main status details first, then the individual GPU status/speeds

Unfortunately, what you call the "main status details" is actually just more detailed information for process number 1. Unless and until we actually make it main/cumulative, it makes most sense to report it where we do now - after the line for child process 1.

BTW, the extra detail would be helpful in more complex cases than yours above - such as when the dupe suppressor is/was enabled, or when speeds change over time and you want to see not only long-term average but also short-term. For what you're running now, you could want to be pressing a key other than `s` to have the one-line status only.

> worth adding a blank line before outputting to show separation between status updates

I'm not so sure (I like to have more information still on screen, rather than scrolled out), but this is something we can do. Perhaps only when running multiple child processes?

> Worth adding a --status-update-timer=60 command to control john automatically showing status every 60 seconds

We already have `--progress-every=60` for this. There's also `AutoStatus` external mode example in `john.conf` showing how you can trigger status display on a programmable condition.

**Comment by solardiz** [comment]
> just more detailed information for process number 1.

Maybe we should be displaying instances of this for all processes (obviously, only when detailed status is requested by `s` keypress), not just for process 1. If we start doing that, we'd need to tie this extra output to the corresponding one-line summaries even closer - should end up with both in the same `write` syscall (or equivalent on non-Unix) - as otherwise they could end up inter-mixed in arbitrary order and it'd be unclear which process number the detailed status corresponds to.

As to eventually having cumulative status detail, this isn't only about combining the stats, but also about having the processes work with more shared data. Right now, the dupe suppressors themselves (and not only their stats) are in fact per-process.

**Comment by blandyuk** [comment]
Ah yes, I remember the status update now, can ignore that one.

I see what you mean about the detailed status on process 1 now, makes sense how it displays. I suppose it does not matter really, as long as it cracks hashes :)

You want me to close this issue?

**Comment by solardiz** [comment]
Let's close this one. If needed, we can open a separate issue for displaying detailed status per-process rather than only for the first process.

**Comment by solardiz** [comment]
> Maybe we should be displaying instances of this for all processes (obviously, only when detailed status is requested by `s` keypress), not just for process 1. If we start doing that, we'd need to tie this extra output to the corresponding one-line summaries even closer - should end up with both in the same `write` syscall (or equivalent on non-Unix)

This is easy - already implemented in my tree. However, actually telling the child processes what kind of status to display isn't so trivial - we use signals, so it'd take e.g. another signal number to communicate this extra bit.

BTW, I'm not sure we want to maintain the current distinction between SIGHUP (update) and SIGUSR2 (reload). Maybe this exists only for historical reasons - one feature was in core, the other added in jumbo. Maybe we want to perform both actions on SIGHUP, which would free up SIGUSR2 e.g. for detailed status. But I won't proceed with this now.

Lots of legacy stuff needing a rewrite here.
