### ISSUE TITLE
No password hashes loaded 

### ISSUE THREAD

**Issue by Amirpy114** [openwall/john#5357]
I get an error when cracking a hash file
`../run/john --format=raw-md5 hash.txt`
error: `Using default input encoding: UTF-8
No password hashes loaded (see FAQ)`
and also crack zip 
Please help me, I need this tool

**Comment by solardiz** [comment]
@Amirpy114 This means your file does not in fact contain a `raw-md5` hash or the file format is wrong. If it's just a sample hash (not security sensitive), you may post the file content in here for others to be able to tell you what exactly is wrong.

For ZIP files, you need to pass them through `zip2john` first.

I'll close this issue since we don't need to track it, but please feel free to add comments.

**Comment by solardiz** [comment]
Another thing to try is simply omitting the `--format=raw-md5` option. Depending on what's in the file, this might end up detecting the correct format, or it could end up using an incorrect format and suggest other options.

> If it's just a sample hash (not security sensitive), you may post the file content in here for others to be able to tell you what exactly is wrong.

If the file content is security sensitive, then instead of posting it you may post the output of these commands:

```
wc hash.txt
head -c 4 hash.txt; echo
```

(the latter will reveal first 4 characters of the file)

**Comment by Amirpy114** [comment]
Maybe I'm wrong because everyone makes mistakes
Please define the steps to install it through Github on Linux from the beginning and I will check it too, if there is a problem again, I will do it again.
Thanks.😊
