### ISSUE TITLE
env: python: No such file or directory 

### ISSUE THREAD

**Issue by iseesec** [openwall/john#5400]
！[上传20231222下午74233.jpg...]()

help. thanks.

**Comment by ghost** [comment]
The message means you don't have `python` installed.

**Comment by iseesec** [comment]
I have installed it.

**Comment by iseesec** [comment]
#
![20231222下午100518](https://github.com/openwall/john/assets/45251884/2b65a11e-2e0b-4d71-bb7d-17861cc953b9)

**Comment by solardiz** [comment]
@iseesec As I understand, you've figured out that you can run those scripts by explicitly running `python3` on them, and so you don't need further help on this, correct?

Speaking of possible changes by projects, it may be that Homebrew's packaging of `john-jumbo` needs to be updated (introduce a `sed -i`?) to change `python` to `python3` in those scripts, if recent Mac systems only have Python under that name - is this so? As to making this change in our project, that's problematic as discussed in #5309.

I'll close this issue since it's not something we need to track now, but please feel free to add comments.

**Comment by iseesec** [comment]
thanks.

  I would say that even if I use python3, I still need to specify the path, such as python3 /opt/homebrew/Cellar/john-jumbo/1.9.0_1/share/john/office2john.py, instead of running python3 office2john.py directly.

  I wanted to try to change this problem with soft connections, but it sucks.


![20231222下午102915](https://github.com/openwall/john/assets/45251884/67522d2b-f054-4251-92dc-b45521c79322)

**Comment by solardiz** [comment]
> even if I use python3, I still need to specify the path, such as python3 /opt/homebrew/Cellar/john-jumbo/1.9.0_1/share/john/office2john.py, instead of running python3 office2john.py directly.

Yes, that's how it is.

You could want to report the problem to Homebrew, and reference this issue, so they're aware of our (upstream) stance on it.

> I wanted to try to change this problem with soft connections, but it sucks.

Per your screenshot, you tried to use symlinks, but somehow got `Operation not permitted` on trying to create a symlink via `sudo ln -s`. I don't know why that failed for you. One possible reason it'd fail is if you do in fact have something named `/usr/bin/python` already. Can you check?

If possible, instead of screenshots please use text copy-paste. You can include text blocks within triple backticks, like this:

```
sudo ln -s /usr/bin/python3 /usr/bin/python
```
