### ISSUE TITLE
Help installing into termux

### ISSUE THREAD

**Issue by Xando01** [openwall/john#5440]
I need help, I'm new to this, like 4 days old new so bare with me. When I go to install it into termux it is giving me something other than what I've been seeing in the YouTube tutorials I've been watching. Can someone please help me out or give me some pointers of what might be going on?

**Comment by solardiz** [comment]
Hi @Xando01. We don't officially support installing into termux - this is third-party stuff, and you didn't provide any detail on the issues you're having, so we can't guess what they are and thus couldn't help even if we supported this. That said, take a look at other issue reports/replies about JtR on termux here: https://github.com/openwall/john/issues?q=termux

We'll likely close this issue shortly since it's not an issue we need to track, but please feel free to add comments anyway.
