### ISSUE TITLE
PBKDF2 With salt Support 

### ISSUE THREAD

**Issue by mightatnight** [openwall/john#5463]
I have a few questions. I can view (or save somewhere)hashed passes that john compares with my hashes?Or john compares it in cl files?
Can i specify pbkdf2-sha512 parameters(salt, iterations)?

**Comment by solardiz** [comment]
> I can view (or save somewhere)hashed passes that john compares with my hashes?

No. The computed hashes are normally never encoded into strings. Instead, the hashes strings loaded for cracking are decoded into binary form and into efficient-for-comparison data structures.

> Or john compares it in cl files?

Where and how exactly the comparison is done varies between "formats", numbers of hashes loaded for cracking, etc.

> Can i specify pbkdf2-sha512 parameters(salt, iterations)?

Yes. For the syntax, you can see some sample encodings with:

```
john --list=format-tests --format=pbkdf2-hmac-sha512
```

**Comment by mightatnight** [comment]
I know about hashes,but i asked where i can view,or enable, for example verbose mode to see the hashes.
About the comparison, it is very important info, I need to know about where the comparison is located in PBKDF2 - SHA512, Also,if u can me told from what number of hashes, john starts comparison in cl code, i will be very grateful.

**Comment by solardiz** [comment]
It could help if you explain the actual problem you're trying to solve.

> i asked where i can view,or enable, for example verbose mode to see the hashes.

So I replied that you cannot.

> I need to know about where the comparison is located in PBKDF2 - SHA512

When you use OpenCL, it's in the `cmp_*` functions in `opencl_pbkdf2_hmac_sha512_fmt_plug.c`.

Edit: but if you load a lot of hashes with the same salt, then it is possible that `cmp_*` would never be reached for wrong guesses, instead relying on bitmap and hash tables. This logic is implemented in `crk_password_loop` in `cracker.c`. Since it's uncommon to have same-salt PBKDF2 hashes, you probably don't have to mess with this, unless your use case is such that you do have such same-salt hashes.

> from what number of hashes, john starts comparison in cl code

In general it's trickier than that, and it varies by hash type, but for `PBKDF2-HMAC-SHA512-opencl` the comparisons are always on host.

I'm closing this issue since it's not something we need to track, but please feel free to add comments.

**Comment by ghost** [comment]
> >  john compares with my hashes?Or john compares it in cl files?
> > i asked where i can view,or enable, for example verbose mode to see the hashes.

In fact, some formats make a partial comparison “inside” the GPU and if a match occurs, these formats only return that a possible crack has occurred. Then on "host" the full hash calculation happens and the final comparison takes place.

Of course, as a developer, you can add a printf inside OpenCL (`.cl`) code and inside the host code (.c). In these situations, you could see a partial hash or some `efficient-for-comparison data structures`. It's good to learn and debug, but it's nowhere near `verbose`.
