### ISSUE TITLE
7z2john.exe missing

### ISSUE THREAD

**Issue by cmdcorp6534** [openwall/john#5514]
There isn't 7z2john.exe in the folder run. How can I use john to crack 7z on Windows?

**Comment by solardiz** [comment]
There is the Perl script `7z2john.pl`, which is what you'd use, even on Windows. You need Perl installed. One way to do this would be by installing Cygwin including its Perl package, then you can simply run `./7z2john.pl` (while in the `run` directory), just like you would on a Unix-like system. Another way is to have only Perl installed and run this script from a usual Windows command prompt, then the command may be like `perl 7z2john.pl` (again while you're in the `run` directory). The latter command should also work under Cygwin.

I'm closing this issue since it's not something we need to track, but please feel free to add comments.

**Comment by aszx1230123zxas-a11y** [comment]
“Is there any video that can help me with the steps or not, or anyone who can talk to me? I need help opening an important file on Windows, but I tried and I can’t.”
