### ISSUE TITLE
The hybrid version of john-the-ripper!

### ISSUE THREAD

**Issue by sojoyork** [openwall/john#5515]
I've been making a mixture of john-the-ripper and hydra (which i named hydra john. I made it because i was bored. Openwall if you are reading this i hope you like it! (hydra-john is a hybrid version of john-the-ripper and hydra).

**Comment by solardiz** [comment]
Hi. Thanks for letting us know. For others reading this, the project is at https://github.com/sojoyork/Hydra-John and is currently just ~100 lines of Python.

If you continue with the project, I think you'll want to document the use cases and functionality. For example:

1. Feeding Hydra with candidate passwords generated by John.
2. Offline password hash cracking with built-in online check whether the cracked password(s) actually let one log in.
3. Online password cracking that is upon successful login followed by password hash file retrieval (how? only if you got the root password and remote root login is allowed?) and offline cracking.

None of this (nor the sinister ideas I refrained from listing) looks very useful - it's probably more reliable and safer to use the tools explicitly - but I understand you like to have fun with this.

I'm closing this issue since it's not something we need to keep track of, but please feel free to add comments.

**Comment by TheKidInYourBasementWhoIsNowWatchingYou** [comment]
Okay, sorry but sojoyork is my brother and he already made it before posting it here :)

**Comment by solardiz** [comment]
Hi. Totally no problem about any of this, nothing you should feel sorry for. It's your project and it's great you guys are having fun.
