### ISSUE TITLE
instlling bsddb3

### ISSUE THREAD

**Issue by Xenoeidos** [openwall/john#5517]
### Checklist ###
- :1st_place_medal: I've read and understood these instructions;
  - This is not a support forum, it's a bug tracker. For questions and support, review postings on the [john-users mailing list](https://www.openwall.com/lists/john-users/).
- :thumbsup: I've tested using latest bleeding version from this repository.
  - Be clear about your environment and what you are doing. Share a sample hash or file that can be used to reproduce.
- :confused: I'm confused and I need guidance.
  - Please, read the instructions at https://www.openwall.com/john/#lists, then join the list before posting.

### IMPORTANT ###
We expect only reports of issues with the latest revision found in this GitHub repository. We do not expect in here, and have little use for, reports of issues only seen in a release or in a distro package.

Attach details about your OS and about john, including:
- The output of `./john --list=build-info`.
- The command line you are using.

im in windows 10 I get this when intaling bug non installing

Collecting bsddb3
  Using cached bsddb3-6.2.9.tar.gz (230 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Editor\AppData\Local\Temp\pip-install-tgyni2nt\bsddb3_c4e97883bd474478a489e84bfb69efe0\setup.py", line 42, in <module>
          import setup3
        File "C:\Users\Editor\AppData\Local\Temp\pip-install-tgyni2nt\bsddb3_c4e97883bd474478a489e84bfb69efe0\setup3.py", line 385, in <module>
          with open(os.path.join(incdir, 'db.h'), 'r') as f :
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'db/include\\db.h'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by solardiz** [comment]
Hi. Why exactly are you installing `bsddb3`? I assume it's to get a specific script of ours working? Which one?

The problem appears to be that you do not have Berkeley DB install (at all, or its "development" sub-package).

I am not familiar with various ways people install Berkeley DB and Python on Windows, but one way that should work is via Cygwin. Also, if you use Python 2 (rather than 3) - which many of our scripts still support - then it comes with a version of Berkeley DB and the Python module bundled. This could be a simpler way for you to get the desired script working sufficiently to achieve your goal.

I'm closing this issue since it's not something we need to track, but please feel free to add comments.
