### ISSUE TITLE
with --fork= and not enough memory, main process can exit before forks leaving them running in background

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#5529]
Messing with running out of memory in #5126, I observed such problem using `--fork=`: if running out of memory happens for the main process then it just exits while other forks keep running. Inconveniently they run in background. I got shell prompt and they sometimes printed something. While they don't print, it is not obvious that they are still running.

`mem_alloc` checks result and quits through `error();`. Similarly any route to `error()` could cause exit in the main process. But most errors happen for all processes symmetrically and almost at the same time. So the inconvenience is not that common and important.

**Comment by solardiz** [comment]
I tentatively set this as "won't fix" and will close for now (we can always reopen). If you want to fix it, please reword as enhancement (like "with --fork, main should kill the rest if exiting on error") and work on fixing it.

I also marked this as a "core branch" issue just because we have the label and that's where the code comes from, but at this time we probably should be fixing (if we do) even core issues in jumbo (as core isn't being maintained separately anymore).

**Comment by solardiz** [comment]
Also, not limited to this issue, @AlekseyCherepanov I appreciate your recent contributions greatly. You can make them even better if each time you open an issue you try and close some other issue (for good reasons, such as through a PR fixing the issue) so that we don't have uncontrolled growth in issue count. I closed some 10% of then-open issues in recent months (we went down from ~510 to ~460 open issues) and I'd appreciate the team's help in closing many more, especially those assigned to a milestone. Thank you!
