### ISSUE TITLE
False positive gcc argument test in configure

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#682]
For some reason the -Qunused-arguments test (added in 471c0e3) fail detecting properly on "super". It detects as supported:

```
checking if gcc supports -Wno-format-extra-args... yes
checking if gcc supports -Qunused-arguments... yes
checking whether ln -s works... yes
```

with this in config.log

```
configure:5880: checking if gcc supports -Qunused-arguments
configure:5902: gcc -c -Werror -Qunused-arguments  -I/usr/local/include conftest.c >&5
gcc: unrecognized option '-Qunused-arguments'
configure:5902: $? = 0
configure:5904: result: yes
```

It seems gcc ends with status code 0 despite -Werror.

During build this leads to hundreds of

```
gcc: unrecognized option '-Qunused-arguments'
gcc: unrecognized option '-Qunused-arguments'
gcc: unrecognized option '-Qunused-arguments'
```

**Comment by AlekseyCherepanov** [comment]
Just for the record because I spent some time to understand the option...

I noticed the following line in output from `./configure`:
```
checking if gcc supports -Qunused-arguments... no
```

Part of `config.log` on gcc 8:
```
configure:6823: checking if gcc supports -Qunused-arguments
configure:6845: gcc -c -Werror -Qunused-arguments  -I/usr/local/include conftest.c >&5
gcc: error: unrecognized command line option '-Qunused-arguments'; did you mean '-Wunused-parameter'?
configure:6845: $? = 1
```

So I thought that the option was renamed. But then I learned that `-Qunused-arguments` is [an option for clang about command line arguments](https://clang.llvm.org/docs/ClangCommandLineReference.html).
> -Qunused-arguments
> Don’t emit warning for unused driver arguments
